### ISSUE TITLE
EKS Fargate support for ALB controller

### ISSUE THREAD

**Issue by kishoreallwynraj** [aws-samples/eks-workshop#1009]
I am currently following https://www.eksworkshop.com/beginner/180_fargate/ as part of the workshop. I have created an Fargate-only cluster, so my “default” and “kube-system” resources are also part of fargate profile. Now when I try to follow the setup of the ALB controller, I see the POD is going to “CrashLoopBackoff”. I checked the POD logs and I found this error. Is this issue due to cluster been created as an Fargate-only cluster?. Does the ALB has to be installed in a namespace which runs on EC2 instance?
 
```
"level":"error","ts":1606563171.2749581,"logger":"setup","msg":"unable to initialize AWS cloud","error":"failed to introspect region from EC2Metadata, specify --aws-region instead if EC2Metadata is unavailable: EC2MetadataRequestError: failed to get EC2 instance identity document
\ncaused by: RequestError: send request failed
\ncaused by: Get \"http://169.254.169.254/latest/dynamic/instance-identity/document\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
```

**Comment by fmedery** [comment]
Thank you for reporting the issue. a PR will be ready soon.

**Comment by psa-jforestier** [comment]
Seems similar to https://github.com/aws-samples/eks-workshop/issues/1003
