### ISSUE TITLE
Private EKS Cluster not accessble

### ISSUE THREAD

**Issue by ashaseenu143** [aws-samples/eks-workshop#1012]
Hi, this is srinivasa am created EKS cluster in AWS using EKSCTL but default it will create public eks (API server endpoint access) but it is i need to change this one into private am trying from AWS console after changing in to private from kube-server where i installed kubectl and eksctl i cant able to access that cluster am getting error tcp:ip ip:443 i/o timeout my kubeserver is in private subnet only and all my worker nodes is also in private only but i dont know why am getting this error from my kube-machine please help me for this to troubleshoot incase u need any info i will provide
EKS-version 1.15
thank you

**Comment by fmedery** [comment]
Hello,
It is a normal behavior to lose access to the EKS cluster from outside de VPC if the EKS public API is disabled.

I would recommend to read more on the topic here:

https://docs.aws.amazon.com/eks/latest/userguide/cluster-endpoint.html
https://medium.com/faun/understanding-amazon-eks-cluster-private-endpoint-access-76ca52bf978a
https://aws.amazon.com/premiumsupport/knowledge-center/eks-public-private-access-api-server/

During this workshop, we use the public endpoint to simplify the initial setup.
