### ISSUE TITLE
310_open_policy_agent/policy-example-1 not creating policy correctly

### ISSUE THREAD

**Issue by shaimona** [aws-samples/eks-workshop#1031]
Following the instruction for creating OPA, it appears that command 

> kubectl create configmap image-source --from-file=image_source.rego
 is not creating policy correctly. The validation command 

> kubectl get configmap image-source -o jsonpath="{.metadata.annotations}"
is not producing any output. 
There is no annotation being generated with the `create configmap` command.

**Comment by SamPooni** [comment]
I am also seeing the same behavior

**Comment by ohookins** [comment]
I have a hunch that to use the `configmap` method of policy configuration, the `kube-mgmt` sidecar is required. I'm not sure that it works with Gatekeeper alone, but I have not had a lot of experience in this area.
