### ISSUE TITLE
update 115_sg-per-pod to use a new nodegroup to get a nitro-based instance type.

### ISSUE THREAD

**Issue by brentley** [aws-samples/eks-workshop#1060]
Security groups for pods are supported by most Nitro-based Amazon EC2 instance families, including the m5, c5, r5, p3, m6g, c6g, and r6g instance families. The t3 instance family is not supported.  

let’s bring up an additional small nodegroup at the beginning of the lesson, then delete it at the end

Let's also include a cost estimation statement for this new nodegroup.

**Comment by dllegru** [comment]
Hi, was just following this workshop `115_sg-per-pod` and it is indeed broken :) as the nodegroup we are using when deploying the eks cluster is composed by `t3.small` as following `030_eksctl` instructions.
Meanwhile this nitro-based nodegroup enhancement is not done, we could just add a note to the workshop that is not going to work with the current t3 nodegroup launched at the beginning.

**Comment by dllegru** [comment]
Hi, was just following this workshop `115_sg-per-pod` and it is indeed broken :) as the nodegroup we are using when deploying the eks cluster is composed by `t3.small` as following `030_eksctl` instructions.
Meanwhile this nitro-based nodegroup enhancement is not done, we could just add a note to the workshop that is not going to work with the current `t3 nodegroup` deployed at the beginning.

**Comment by fmedery** [comment]
@brentley I will propose a PR tomorrow evening to fix the lab
