### ISSUE TITLE
intermediate/290_argocd/configure: ARGOCD_SERVER null

### ISSUE THREAD

**Issue by liammurray** [aws-samples/eks-workshop#1073]
There is a timing issue with this. (Mine was set null.) You may wish to warn people that it may take time before the LoadBalancer shows up.

```
kubectl patch svc argocd-server -n argocd -p '{"spec": {"type": "LoadBalancer"}}'
export ARGOCD_SERVER=`kubectl get svc argocd-server -n argocd -o json | jq --raw-output .status.loadBalancer.ingress[0].hostname`
```

**Comment by fmedery** [comment]
Thank you for reporting. 
#1104 and #1073 has been pushed to fix some argo problem
