### ISSUE TITLE
Create ExternalDNS tutorial

### ISSUE THREAD

**Issue by joebowbeer** [aws-samples/eks-workshop#1076]
I suggest adding a segment on [ExternalDNS](https://github.com/kubernetes-sigs/external-dns)

It is listed on EKS's related projects page:

https://docs.aws.amazon.com/eks/latest/userguide/related-projects.html

and Containers From The Couch did a segment about it:

[How to use external-dns to manage your Kubernetes resource names](https://youtu.be/3sUsZq1TA2g)

**Comment by dnltinney** [comment]
Yes, I would also love to see externalDNS on the eks-workshopt 👍
