### ISSUE TITLE
Troubleshooting Your Service Mesh with Kiali

### ISSUE THREAD

**Issue by sheetaljoshi** [aws-samples/eks-workshop#1116]
Add "Troubleshooting Service Mesh with Kiali" to the "EKS Workshop"; chapter "Service Mesh with Istio." Rework the "Monitor & Visualize" page to include Jaeger installation, as well as any steps in this section that need to be changed to use and install self-managed Prometheus, Grafana, and Jaeger as Istio add-ons mentioned here (https://istio.io/latest/docs/setup/getting-started/). Also install Kiali add-on.

Create a new section that demonstrates how to customize Istio to expose and access telemetry add-ons outside of a cluster, refer here (https://istio.io/latest/docs/tasks/observability/gateways/). 

Add a guide (https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/istio.md) about how to setup ExternalDNS to use the Istio Gateway source. These steps will create records under previously registered domain and hosted zones. Clean up will also demonstrate how externalDNS entries get automatically deleted as Istio resources are deleted.

**Comment by Jukie** [comment]
@sheetaljoshi are you still working on this? If not I'd like to pick it up.

**Comment by saleem-mirza** [comment]
This feature request has been partially addressed in https://github.com/aws-samples/eks-workshop/pull/1161

**Comment by sheetaljoshi** [comment]
@Jukie I have the yamls ready, but I have to submit the code, I have not done that! Plese feel free to own. I will commit the externalDNS changes, if you would like me to.
