### ISSUE TITLE
Use Environment Variables in all Scripts/JSON for Virtual Cluster ID, EMR IAM Role etc.

### ISSUE THREAD

**Issue by vijayansarathy** [aws-samples/eks-workshop#1121]
Under the Monitoring and Logging Part 1 section, we need instructions that request.json should be modified based on the virtual cluster ID, IAM role ARN and S3 bucket name per the user’s environment or provide the command to create that using VIRTUAL_CLUSTER_ID, EMR_ROLE_ARN and S3_BUCKET_NAME and environment variables.

**Comment by dalbhanj** [comment]
@prabhatsharma, can you take a look at this issue?

**Comment by youngjeong46** [comment]
submitted PR #1219
