### ISSUE TITLE
Worker Node Instance Size for EMR on EKS Cluster

### ISSUE THREAD

**Issue by vijayansarathy** [aws-samples/eks-workshop#1122]
Under the Monitoring and Logging Part 1 section, the Spark job configuration has **spark.executor.cores** is set to 2. With this setting, the jobs did not run and were stuck in a Pending state when using a **m5.large** cluster because there was not enough CPU. In a previous example in this section, this was set to 1. When I made the change, the job ran to completion. 

Either use this setting @ 1 or use larger instances with more vCPUs.

**Comment by dalbhanj** [comment]
Newer chapter on Spot will address this issue

**Comment by dalbhanj** [comment]
PR fix by adding new node group applied
