### ISSUE TITLE
Prometheus Metrics and PromQL Expression for Grafana

### ISSUE THREAD

**Issue by vijayansarathy** [aws-samples/eks-workshop#1123]
Under Monitoring and Logging Part 2 (Prometheus & Grafana) section, it says “**Import the dashboard 11674**”. Looks like you are referring to pre-built Grafana dashboard, perhaps? I was using an Prometheus & Grafana installation already have running in my cluster but did not know which metric to look for. I used _kubectl port-forward_ on the Prometheus server pod and browsed directly to the Prometheus server UI but did not see any metrics that appeared to be related to the Spark jobs. 

I suggest that you explicitly point out the name of the Prometheus metric(s) here and also point out the PromQL query to be used when setting up the dashboard in Grafana.

**Comment by dalbhanj** [comment]
@prabhatsharma, can you take a look at this issue?
