### ISSUE TITLE
Configure CNI - command not correct

### ISSUE THREAD

**Issue by mailneerajibm** [aws-samples/eks-workshop#1165]
Hello team,

While testing EKS workshop, Beginner section: Advanced Networking - Configure CNI page, Below command is not correct:

INSTANCE_IDS=(`aws ec2 describe-instances --query 'Reservations[*].Instances[*].InstanceId' --filters "Name=tag-key,Values=eks:cluster-name" "Name=tag-value,Values=eksworkshop*" --output text` )

Using above command the INSTANCE_IDS variable points to only one instance id. It should be like below to hold the list of all instance IDs.

The round brackets at start and end of command is the problem. 

proposed solution (tested and working fine see screenshot)

INSTANCE_IDS=`aws ec2 describe-instances --query 'Reservations[*].Instances[*].InstanceId' --filters "Name=tag-key,Values=eks:cluster-name" "Name=tag-value,Values=eksworkshop*" --output text` 

Using above command INSTANCE_IDS will hold list of all instance ids.

Please see the screenshots attached to verify the issue and solution.

![EKS Workshop Immersion  Day Issue 1](https://user-images.githubusercontent.com/37997251/120464887-0d0a1f80-c3bb-11eb-893a-30cb9cbd4fec.JPG)
![EKS Workshop Immersion  Day Solution](https://user-images.githubusercontent.com/37997251/120464907-11ced380-c3bb-11eb-9f1e-496c33b30573.JPG)

**Comment by mailneerajibm** [comment]
Pull request created for the same, #1166

**Comment by Jukie** [comment]
The existing code creates an array so your example isn't valid, to show the rest of the ids you'd need to specify an array index or loop through them like the existing code.
For example:
```
$ echo ${INSTANCE_IDS[2]}
i-0901e0dabf33977d0
```
Versus the below which only shows the first id:
```
$ echo $INSTANCE_IDS 
i-036ebe3fa2a4e6d17
```

The existing code successfully terminates all instances.
