### ISSUE TITLE
[EMR on EKS] Configure Autoscaling

### ISSUE THREAD

**Issue by xwng** [aws-samples/eks-workshop#1182]
Before submitting the job with Dynamic Resource Allocation (DRA) enabled, the previous job should run to  completion. Otherwise the output of watch command may show pods from the  earlier spark job

Ask user to wait for some time after the command "watch kubectl get pods -n spark"

**Comment by jamalarif** [comment]
Submitted pull request https://github.com/aws-samples/eks-workshop/pull/1188
