### ISSUE TITLE
Issue: Setup AWS Load Balancer Controller on Fargate Chapter

### ISSUE THREAD

**Issue by lusoal** [aws-samples/eks-workshop#1200]
Error when create the CRD's for the Target Group Biding:

Error:

```shell
zsh: no matches found: github.com/aws/eks-charts/stable/aws-load-balancer-controller//crds?ref=master
```

Solution:

```sh
kubectl apply -k "github.com/aws/eks-charts/stable/aws-load-balancer-controller/crds?ref=master"
```

Instead of:

```sh
kubectl apply -k github.com/aws/eks-charts/stable/aws-load-balancer-controller//crds?ref=master
```

**Comment by nirmalyaster** [comment]
Hi lusoal,

Thanks for posting the issue. I have ran the same setup as mentioned in [eksworkshop](https://www.eksworkshop.com/beginner/130_exposing-service/ingress_controller_alb/) in a cloud9 environment.

However, it did not give any error. 
![aws load balancer controller issue](https://user-images.githubusercontent.com/6679901/127347254-202758b2-92c0-4e8c-b6b8-0237b338b4b4.png)

In case you are using a different bash shell/environment details - please let me know.
