### ISSUE TITLE
While deploying with ekscluster, you receive an error that it's unable to connect to the cluster, getting credentials expects v1alpha1 but gets v1beta1

### ISSUE THREAD

**Issue by scouturier** [aws-samples/eks-workshop#1232]
Deploying with ekscluster outputs the following error:
_unable to use kubectl with the EKS cluster (check 'kubectl version'): Unable to connect to the server: getting credentials: exec plugin is configured to use API version client.authentication.k8s.io/v1alpha1, plugin returned version client.authentication.k8s.io/v1beta1_

As a workaround, when the cluster is done deploying, running this command will fix this:
`
aws eks update-kubeconfig --name eksworkshop-eksctl
`

**Comment by scouturier** [comment]
The AWS CLI V2 was [recently updated](https://github.com/aws/aws-cli/pull/6289) and the version for the credential API changed from v1alpha1 to v1beta1

**Comment by ROunofF** [comment]
Fix by CLI update
