### ISSUE TITLE
Cluster Autoscaler instruction not working correctly for latest k8s version

### ISSUE THREAD

**Issue by praseedasathaye** [aws-samples/eks-workshop#1259]
In the Cluster Scaling part of the lab the instructions haven’t aged well either. For example: https://www.eksworkshop.com/beginner/080_scaling/deploy_ca/#deploy-the-cluster-autoscaler-ca
The logic for determining the autoscaler version doesn’t work anymore, because the EKS cluster is version 1.17.x and the corresponding autoscaler release has gone beyond the first page of results returned by the GitHub API. The doc says:
```
kubectl -n kube-system \
    set image deployment.apps/cluster-autoscaler \
    cluster-autoscaler=us.gcr.io/k8s-artifacts-prod/autoscaling/cluster-autoscaler:v${AUTOSCALER_VERSION}```

And because of this this env variable image is empty.

And also when we update the image to match with k8s version, autoscaler container is getting OOMKilled because of the limit issue in this file https://www.eksworkshop.com/beginner/080_scaling/deploy_ca.files/cluster-autoscaler-autodiscover.yaml

**Comment by buzzsurfr** [comment]
This is happening because GitHub API only returns the last 30 releases, and our kubernetes cluster is now on a version that is past the 30 release count.

As a workaround, you can run:
```
export AUTOSCALER_VERSION=1.17.3
```

as a workaround until this is fixed.

**Comment by praseedasathaye** [comment]
I tried that with 1.17 but autoscaler container is getting OOMKilled because of the memory limit issue as we use this file https://www.eksworkshop.com/beginner/080_scaling/deploy_ca.files/cluster-autoscaler-autodiscover.yaml in the workshop.

**Comment by andreyzher** [comment]
There is actually a PR (#1250) that should resolve the OOMKilled issue - I had increased the request/limit to 500Mi during the workshop and it was sufficient.

**Comment by ROunofF** [comment]
This was fix with update + adjustement to request/limit
