### ISSUE TITLE
cloudformation template urls are not working.

### ISSUE THREAD

**Issue by akramshaik541** [aws-samples/eks-workshop#1314]
The cloud formation template URLs mentioned in the docs are expired.

example:
[weave_flux_pipeline.cfn.yml](https://s3.amazonaws.com/eksworkshop.com/templates/main/weave_flux_pipeline.cfn.yml)
[ci-cd-codepipeline.cfn.yml](https://s3.amazonaws.com/eksworkshop.com/templates/main/ci-cd-codepipeline.cfn.yml)

**Comment by GAcharyaOS** [comment]
I'm encountering the same issue.. Is there a fix or workaround to this ? how to get access to the codepipeline yaml ?
