### ISSUE TITLE
Windows containers on EKS lab issues and fixes

### ISSUE THREAD

**Issue by GAcharyaOS** [aws-samples/eks-workshop#1322]
**"Windows containers on EKS" lab in EKS workshop is broke because of following issues :**
        1. "Windows Nodes" section of the lab referencing unsupported version of windows AMI.  
        2. Format for powershell command param in the YAML doesn't account for escape characters, hence will fail in parsing in executing the steps under "Deploy an application" section of the lab.
        3. the URL for docker image in the yaml pointing to an old image in registry and hence fail in creating Windows Pod

Below are the steps to fix the lab:

**Steps to follow to fix issue # 1 above :** 
a. Refer AMI release calendar and list of supported AMIs at https://docs.aws.amazon.com/eks/latest/userguide/eks-optimized-windows-ami.html , and identify the AMI family based on your region and version of Kubernetes in your env. 
b. To point to appropriate AMI family, update "amiFamily" tag in windows_nodes.yaml created as part of steps under "Windows Nodes" section. For e.g. for us-east-1 and K8 version 1.19.x, the amiFamily according to current supported ami matrix is WindowsServer2019CoreContainer.
c. Rerun the following command to creating the node group : 
         eksctl create nodegroup -f ~/environment/windows/windows_nodes.yaml
d. continue with the lab until you hit issue # 2 above.

**Steps to follow to fix issue # 2 and # 3 above :** 
a.  Replace the value passed to command param of powershell.exe in windows_server_iis.yaml file with the following:
       "Add-WindowsFeature Web-Server; Invoke-WebRequest -UseBasicParsing -Uri 'https://dotnetbinaries.blob.core.windows.net/servicemonitor/2.0.1.6/ServiceMonitor.exe' -OutFile 'C:\\ServiceMonitor.exe'; echo '<html><body><br/><br/><marquee><H1>Hello EKS!!!<H1><marquee></body><html>' > C:\\inetpub\\wwwroot\\default.html; C:\\ServiceMonitor.exe 'w3svc';"

     Note - that value should have an escape char for backslash such that it is C:\\ and not C:\

b. Replace the image url to point to correct docker image based on the AMI family. For e.g. if amiFamily is WindowsServer2019CoreContainer, the image tag should be  mcr.microsoft.com/windows/servercore:ltsc2019
c. Re-run following command to apply the changes:
        kubectl apply -f ~/environment/windows/windows_server_iis.yaml
d. continue with rest of steps from the lab.

**Comment by jansony1** [comment]
still not work for "2. Format for powershell command param in the YAML doesn't account for escape characters, hence will fail in parsing in executing the steps under "Deploy an application" section of the lab.
"
