### ISSUE TITLE
Calico manifest link broken

### ISSUE THREAD

**Issue by kishgau** [aws-samples/eks-workshop#1385]
On https://www.eksworkshop.com/beginner/120_network-policies/calico/install_calico/,
the url to manifest seems to be broken
kubectl apply -f https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/master/config/v1.6/calico.yaml

**Comment by pjlewisuk** [comment]
Hi @kishgau , if you fix and submit a PR, happy to review and merge
