### ISSUE TITLE
architectural visuals for migrate_to_eks content

### ISSUE THREAD

**Issue by kayalvizhiameen** [aws-samples/eks-workshop#1408]
The Immersion Lab content - https://www.eksworkshop.com/intermediate/200_migrate_to_eks/ does not have any architectural visuals and it consumes good amount of time to explain the idea with white-boarding tools while running it through with our customers. A crisp visual representation would help the presenter to communicate it effectively and audience could grasp it easily (picture speaks louder than words)

**Comment by ROunofF** [comment]
Thanks for the addition!
