### ISSUE TITLE
cluster-autoscaler-autodiscover image location is incorrect

### ISSUE THREAD

**Issue by gr8sk8s** [aws-samples/eks-workshop#1423]
The current code in cluster-autoscaler-discover.yaml (line 141) shows as:
` - image: k8s.gcr.io/cluster-autoscaler:v1.20`

**Issue**:
When deploying this, users run into the following error (event seen in kube-system): 
`Warning ... Failed to pull image "k8s.gcr.io/cluster-autoscaler:v1.20.0" ... manifest unknown ....`

**Recommended fix**:
Update the image path;  change it to the following which deploys successfully: 
` - image: k8s.gcr.io/autoscaling/cluster-autoscaler:v1.20.3`

**Comment by ROunofF** [comment]
Fix in #1467
