### ISSUE TITLE
260_weave_flux lab Deploy from Helm yaml file issue 

### ISSUE THREAD

**Issue by jchenzhi** [aws-samples/eks-workshop#1461]
260_weave_flux lab - step "Deploy from Helm" helm release yaml file deployment failed. 

ts=2022-07-13T21:11:10.742944624Z caller=release.go:316 component=release release=mywebserver targetNamespace=nginx resource=nginx:helmrelease/mywebserver helmVersion=v3 error="installation failed: Deployment.apps \"mywebserver-nginx\" is invalid: [spec.template.spec.containers[0].livenessProbe.tcpSocket: Forbidden: may not specify more than 1 handler type, spec.template.spec.containers[0].readinessProbe.tcpSocket: Forbidden: may not specify more than 1 handler type]" phase=install
ts=2022-07-13T21:11:10.742988105Z caller=release.go:422 component=release release=mywebserver targetNamespace=nginx resource=nginx:helmrelease/mywebserver helmVersion=v3 info="running uninstall" phase=uninstall
ts=2022-07-13T21:11:10.754975811Z caller=helm.go:69 component=helm version=v3 info="uninstall: Deleting mywebserver" targetNamespace=nginx release=mywebserver
ts=2022-07-13T21:11:10.944815111Z caller=helm.go:69 component=helm version=v3 info="Starting delete for \"mywebserver-nginx\" Service" targetNamespace=nginx release=mywebserver
ts=2022-07-13T21:11:10.97485752Z caller=helm.go:69 component=helm version=v3 info="Starting delete for \"mywebserver-nginx\" Deployment" targetNamespace=nginx release=mywebserver
ts=2022-07-13T21:11:10.979669095Z caller=helm.go:69 component=helm version=v3 info="deployments.apps \"mywebserver-nginx\" not found" targetNamespace=nginx release=mywebserver
ts=2022-07-13T21:11:10.979713337Z caller=helm.go:69 component=helm version=v3 info="purge requested for mywebserver" targetNamespace=nginx release=mywebserver

**Comment by ROunofF** [comment]
Thanks for reporting this, closing as appears fixed
