### ISSUE TITLE
060_helm/helm_micro/deploy - error: 'nil pointer evaluating interface {}.port'

### ISSUE THREAD

**Issue by ahmedcatic** [aws-samples/eks-workshop#1472]
At this step, using Cloud9:
https://www.eksworkshop.com/beginner/060_helm/helm_micro/deploy/

Having reviewed it a few times, I believe I've followed the relatively simple procedure accurately, based on the text as well as the videos.  Whenever I try to do the dry run, I get the result below.  I've read other forums about this general error, suggesting some Go or Helm version issue, or to try nesting the variables or moving them up a level.  Thanks in advance for all guidance in clearing it up.

:~/environment/eksdemo $ helm install --debug --dry-run workshop ~/environment/eksdemo
install.go:178: [debug] Original chart version: ""
install.go:195: [debug] CHART PATH: /home/ec2-user/environment/eksdemo

Error: INSTALLATION FAILED: template: eksdemo/templates/tests/test-connection.yaml:14:59: executing "eksdemo/templates/tests/test-connection.yaml" at <.values.service.port>: nil pointer evaluating interface {}.service
helm.go:84: [debug] template: eksdemo/templates/tests/test-connection.yaml:14:59: executing "eksdemo/templates/tests/test-connection.yaml" at <.values.service.port>: nil pointer evaluating interface {}.service
INSTALLATION FAILED
main.newInstallCmd.func2
        helm.sh/helm/v3/cmd/helm/install.go:127
github.com/spf13/cobra.(*Command).execute
        github.com/spf13/cobra@v1.4.0/command.go:856
github.com/spf13/cobra.(*Command).ExecuteC
        github.com/spf13/cobra@v1.4.0/command.go:974
github.com/spf13/cobra.(*Command).Execute
        github.com/spf13/cobra@v1.4.0/command.go:902
main.main
        helm.sh/helm/v3/cmd/helm/helm.go:83
runtime.main
        runtime/proc.go:255
runtime.goexit
        runtime/asm_amd64.s:1581

**Comment by ahmedcatic** [comment]
Either delete this or leave it for posterity, but of course ---- I just redid it, this time COPYING everything instead of typing it manually (for experience), and it worked.

**Comment by ROunofF** [comment]
Thanks for the input! Glad you were able to go through it!
