### ISSUE TITLE
Unable to get 500s per instructions

### ISSUE THREAD

**Issue by geremyCohen** [aws-samples/eks-workshop#151]
Following:

https://eksworkshop.com/servicemesh/routing/

Following these directions, I am unable to get 500s.

> The subset is set to v1 by default and returns a 500 HTTP error for all requests if the logged user matches with **jason** for ratings.
> ...
> Click **Sign in** from the top right corner of the page and login using **jason** as user name with a blank password. You will see error for ratings. Others will see rating without error.

**Comment by geremyCohen** [comment]
Addressing in https://github.com/aws-samples/eks-workshop/commit/8683fe9af2fe5779ad3a725cf546978e6eca16f2

**Comment by brentley** [comment]
Thanks for the rewording -- closing now.
