### ISSUE TITLE
unexpected status "ROLLBACK_IN_PROGRESS" while waiting for CloudFormation Stack error

### ISSUE THREAD

**Issue by carnate-tech** [aws-samples/eks-workshop#1510]
An error was encountered during the creation of the CloudFormation stack. Instruction on how to clean up is not working too. Please see attached error. 
<img width="947" alt="eks error" src="https://user-images.githubusercontent.com/71613903/199106394-eec72987-9afe-4d21-bc25-0b5b32679897.PNG">

**Comment by ROunofF** [comment]
We recommend to check through the console for the cloudformation stack. You can delete it from there before retrying.
