### ISSUE TITLE
Canary deployment using Istio and Spinnaker

### ISSUE THREAD

**Issue by dalbhanj** [aws-samples/eks-workshop#18]

**Comment by gmarchand** [comment]
It would be interesting to compare each method : 
- Spinnaker
- Argo
- Flux
- GitOps Engine
- Gitlab https://docs.gitlab.com/ee/user/project/canary_deployments.html
- other ? AppMesh

Which alerts ? 
- Lambda hook
- Cloudwatch alarms 
- Clouwatch Synthetics

**Comment by dalbhanj** [comment]
This issue was created a while ago (~2 years). Closing this issue for now.
