### ISSUE TITLE
Mention the ability to customize the kubectl editor

### ISSUE THREAD

**Issue by bellkev** [aws-samples/eks-workshop#182]
When [setting up the Argo artifact repository](https://eksworkshop.com/batch/artifact/), `kubectl edit` is used. It could be useful to point out that you can customize the editor `kubectl` uses like this:

```
KUBE_EDITOR="nano" kubectl edit svc/docker-registry   # Use an alternative editor
```

This could be helpful for folks who aren't familiar with `vi`, which seems to be the default in Cloud9.

**Comment by fmedery** [comment]
Thank you for reporting this issue. We updated the lab to the latest version argo and we now use `kubectl patch` instead of `kubectl edit` #864
