### ISSUE TITLE
Github username for Codepipeline CFT is case sensitive

### ISSUE THREAD

**Issue by ZacharyWallace** [aws-samples/eks-workshop#186]
See title. If a user does not enter their username in the correct case then the pipeline will fail to fetch code from Github.

The instructions should call out case sensitivity.

**Comment by buzzsurfr** [comment]
Issue refers to https://eksworkshop.com/codepipeline/codepipeline/, specifically:
https://github.com/aws-samples/eks-workshop/blob/21f03a2066d80e266aa86987bf294e56aa8c0b7e/content/codepipeline/codepipeline.md#L26

Callout to add  "(case sensitive)" after "_Github username_"

**Comment by rnzsgh** [comment]
Thanks for submitting this issue. I'll update the docs.
