### ISSUE TITLE
make it more clear where to click to for the "at an event" use case

### ISSUE THREAD

**Issue by geremyCohen** [aws-samples/eks-workshop#187]
In https://eksworkshop.com/prerequisites/aws_event/portal/

At the bottom in very small text, it says:

```
Once you have completed the step above, you can head straight to Create a SSH key section
```

If the user doesn't see this, they could click next instinctively, which may not be the desired action.

We should make this flow improved.

**Comment by buzzsurfr** [comment]
This workflow was revised to optimize the user attending an AWS event (e.g. we moved the "...at an AWS event" below "...on your own" so that the next button continues into "Create a SSH key").
