### ISSUE TITLE
role needs to be configured to allow services access by dashboard user

### ISSUE THREAD

**Issue by geremyCohen** [aws-samples/eks-workshop#190]
In https://eksworkshop.com/dashboard/dashboard/ where we deploy the dashboard, the role permissions don't allow the logged in dashboard user to view services.

**Comment by buzzsurfr** [comment]
I was unable to recreate this scenario, can you post steps taken to recreate?

**Comment by geremyCohen** [comment]
I just tried to repro as well, unable to.  Strange, as I had run into it before myself, and had seen attendees running into it as well.  Will re-open if I can find a way to repro.
