### ISSUE TITLE
make it more clear on what text should not be copied/saved

### ISSUE THREAD

**Issue by geremyCohen** [aws-samples/eks-workshop#192]
In https://eksworkshop.com/deploy/applications/ a user may feel they need to take action on the displayed text, due to the language on the page, and the fact there is a copy icon on the snippet.

We should make it more clear that this is example text, and it should only be examined, not saved or acted up.

**Comment by geremyCohen** [comment]
Another example where this should be pointed out:

https://eksworkshop.com/deploy/servicetype/

**Comment by brentley** [comment]
We can remove the copy icon.
