### ISSUE TITLE
clean up structure around cat command, and what it does

### ISSUE THREAD

**Issue by geremyCohen** [aws-samples/eks-workshop#200]
in https://eksworkshop.com/calico/stars_policy_demo/create_resources/

at

```
Let’s examine our file by running cat namespace.yaml.

kind: Namespace
apiVersion: v1
metadata:
  name: stars

Create a namespace called stars:

```

cat command should be copy/pasteable, and the yaml body should not be.

**Comment by geremyCohen** [comment]
further down as well:

```
cat management-ui.yaml:

```

**Comment by geremyCohen** [comment]
https://eksworkshop.com/calico/stars_policy_demo/apply_network_policies/

```
Let’s examine our file by running cat default-deny.yaml.
```

**Comment by geremyCohen** [comment]
https://eksworkshop.com/calico/stars_policy_demo/directional_traffic/

```
Let’s examine this backend policy with cat backend-policy.yaml:
```

**Comment by brentley** [comment]
I believe this has been addressed with a recent edit. Please reopen if it's still a problem.
