### ISSUE TITLE
Spin up elastic-cache service automatically

### ISSUE THREAD

**Issue by aabrahamian** [aws-samples/eks-workshop#203]
It would be nice if the Elasticsearch cluster was already up so I (and others) wouldn't have to wait 10 minutes for its creation. I understand that we want to inform people about the steps to create but it would be nice to have one that it is ready to go.

@geremyCohen is responsible for this
He said please assign to him and have him fix it

**Comment by oak2278** [comment]
I see your point, but as the module is written, the expectation is that you will quickly kick off the cluster creation and then move on with other steps. This means that by the time you need it, it's already provisioned. 

Personally I find the value of the ElasticSearch (ES) cluster to be somewhat limited given the cost of the for self-paced participants. This could be listed as an optional step and end the module with CloudWatch Logs inspection for those who aren't interested in using ES
