### ISSUE TITLE
HPA lab setup not working

### ISSUE THREAD

**Issue by aimanparvaiz** [aws-samples/eks-workshop#205]
I am using Terraform to setup EKS cluster (https://registry.terraform.io/modules/terraform-aws-modules/eks/aws/1.7.0). Everything goes fine except that I cant get HPA working following this lab: https://eksworkshop.com/scaling/test_hpa/.
I was seeing the following on kubectl describe hpa php-apache

```Events:
  Type     Reason                        Age                From                       Message
  ----     ------                        ----               ----                       -------
  Warning  FailedGetResourceMetric       5m (x31 over 20m)  horizontal-pod-autoscaler  unable to get metrics for resource cpu: no metrics returned from resource metrics API
  Warning  FailedComputeMetricsReplicas  6s (x41 over 20m)  horizontal-pod-autoscaler  failed to get cpu utilization: unable to get metrics for resource cpu: no metrics returned from resource metrics API
```

I got it working using the following: https://github.com/kubernetes-incubator/metrics-server/issues/131#issuecomment-418613256.

**Comment by buzzsurfr** [comment]
## Steps to Recreate
- Spun up a new Cloud9 IDE
- Launch using eksctl
- Install Helm using helm module
- Deploy the Metrics server, create/autoscale `php-apache`.

## Troubleshooting/fix
Traced the problem down to [a bug in metrics-server](https://github.com/kubernetes-incubator/metrics-server/issues/90) v0.3.0, which is used by chart v2.0.2. Updating to chart v2.0.4 (metrics-server v0.3.1) fixes the problem. Will submit PR.
