### ISSUE TITLE
Getting helm error when deploying site.

### ISSUE THREAD

**Issue by awshenry** [aws-samples/eks-workshop#210]
.  I am getting the following when I am trying to deploy the services via Helm:
 
Admin:~/environment/eksdemo2 $ helm install --debug --dry-run --name workshop ~/environment/eksdemo
[debug] Created tunnel using local port: '45233'
 
[debug] SERVER: "127.0.0.1:45233"
 
[debug] Original chart version: ""
[debug] CHART PATH: /home/ec2-user/environment/eksdemo
 
Error: render error in "eksdemo/templates/tests/test-connection.yaml": template: eksdemo/templates/tests/test-connection.yaml:4:12: executing "eksdemo/templates/tests/test-connection.yaml" at <include "eksdemo.ful...>: error calling include: template: no template "eksdemo.fullname" associated with template "gotpl"

**Comment by buzzsurfr** [comment]
Presumably fixed by #208, please confirm.

**Comment by fmedery** [comment]
Thank you for the feedback and the fix.
`Helm` module is now using V3. #661
