### ISSUE TITLE
Update Kubernetes dashboard URL

### ISSUE THREAD

**Issue by yossij** [aws-samples/eks-workshop#219]
The Kubernetes dashboard URL returns 404:
https://github.com/aws-samples/eks-workshop/blame/master/content/dashboard/dashboard.md#L12

This is the new link:
`https://raw.githubusercontent.com/kubernetes/dashboard/master/aio/deploy/recommended/kubernetes-dashboard.yaml`

**Comment by vjsikha** [comment]
addressed in #218
