### ISSUE TITLE
Logging Module: There was a problem There was an error creating your Lambda Function. Please try again.

### ISSUE THREAD

**Issue by christensen143** [aws-samples/eks-workshop#220]
I keep getting 

There was a problem
There was an error creating your Lambda Function. Please try again.

When attempting to create the stream. I have copied and pasted everything as shown. I am using us-east-2 so I changed the REGION env in fluentd.yml.

Any idea what I'm missing?

**Comment by christensen143** [comment]
I found a work around for this on the AWS forums. Basically you create the function manually and then subscribe. https://forums.aws.amazon.com/thread.jspa?threadID=295573

**Comment by fmedery** [comment]
Closing this issue for now,
@christensen143 don't hesitate to reopen the issue if needed.
