### ISSUE TITLE
Script in the EFK module is not aligned with the name of the workers cloud formation stack

### ISSUE THREAD

**Issue by groovymood** [aws-samples/eks-workshop#227]
Logging with Elasticsearch, Fluentd, and Kibana (EFK) module contains the following script

INSTANCE_PROFILE_PREFIX=$(aws cloudformation describe-stacks --stack-name eksctl-eksworkshop-eksctl-nodegroup-0

However the name of the stack created by EKSCTL earlier is not eksctl-eksworkshop-eksctl-nodegroup-0 but eksctl-eksworkshop-eksctl-nodegroup-<random suffix> 

therefore it doesn't work

**Comment by Zvikan** [comment]
trying with` eksctl-eksworkshop-eksctl-nodegroup-` won't work as describe-stacks requires specific stack name.
Instead what I did :
`INSTANCE_PROFILE_PREFIX=$(aws cloudformation describe-stacks | jq -r .Stacks[].StackName | grep eksctl-eksworkshop-eksctl-nodegroup)`

this can also be achieved by using query search via CLI, something like `--query "Stacks[?contains(StackName,'eksctl-eksworkshop-eksctl-nodegroup')].StackName"`

From my side I had to add `--region us-west-2 ` as If I wouldn't C9 didnt set AWS_REGION automatically as expected, this is related to a diff issue: 
https://github.com/aws-samples/aws-workshop-for-kubernetes/issues/543

**Comment by brentley** [comment]
I believe this was addressed with recent updates. Please reopen if it's still an issue.
