### ISSUE TITLE
Use exsiting microservices in Calico section

### ISSUE THREAD

**Issue by liljenstolpe** [aws-samples/eks-workshop#239]
We have already setup some basic microservices for other aspects of the eks workshop.  What would people think if we used those micro services for the Calico/network policy section, rather than the stars demo?  If  it's a good idea, I can do the work...

**Comment by dalbhanj** [comment]
Hi @liljenstolpe, this is really cool idea. Happy to review content when its ready

**Comment by liljenstolpe** [comment]
Ok - sorry about the delay on getting back to this, but will do so in the next few days.
