### ISSUE TITLE
Add chapter on App Mesh

### ISSUE THREAD

**Issue by geremyCohen** [aws-samples/eks-workshop#240]
Customer has requested App Mesh.

**Comment by geremyCohen** [comment]
I'm on it!

**Comment by deki** [comment]
Thanks @geremyCohen for the work done so far. I was trying to run it in `eu-west-1` region and it didn't work. I just noticed that `us-west-2` region is hardcoded in [colorapp.yaml](https://raw.githubusercontent.com/geremyCohen/colorapp/master/colorapp.yaml). Shall we add a note for that?

**Comment by geremyCohen** [comment]
Hi!  Yes, I am working on a completely new version of the tutorial, and it will call out region-specific settings more explicitly.
