### ISSUE TITLE
port in use error when port forwarding for grafana

### ISSUE THREAD

**Issue by geremyCohen** [aws-samples/eks-workshop#247]
On https://eksworkshop.com/servicemesh/visualize/

at step:

```
kubectl -n istio-system port-forward $(kubectl -n istio-system get pod -l app=grafana -o jsonpath='{.items[0].metadata.name}') 8080:3000 &

```

A port in use error is displayed.

**Comment by geremyCohen** [comment]
This is because user did not exit previous port forward (backgrounded) process (potentially from Dashboard or Istio exercises).  Fix is to foreground and CTRL-C (or kill any other way) that previously backgrounded process.

**Comment by geremyCohen** [comment]
Will add note to docs

**Comment by fmedery** [comment]
Bug fixed, closing the issue.
