### ISSUE TITLE
Grafana Enhancement

### ISSUE THREAD

**Issue by AAber** [aws-samples/eks-workshop#264]
# Setup two Grafana dashboards
The dashboards are fully functional and show lots of useful info about the k8s cluster.
The dashboard IDs are 3119 and 6417, see screenshots below.

Use Helm to install prometheus-operator
`helm install --name prometheus --namespace monitoring stable/prometheus-operator`

Proxy into Grafana dashboard:
`kubectl --namespace monitoring port-forward $(kubectl get pods -n monitoring|grep grafana|awk '{print $1}') 3000 & `

http://localhost:3000
u: admin
p: prom-operator

Then add the two dashboards to Grafana.

![image](https://user-images.githubusercontent.com/4179519/52285213-a0a7be80-296e-11e9-8d17-bf59fc7c88a7.png)
![image](https://user-images.githubusercontent.com/4179519/52285273-b917d900-296e-11e9-8d92-8203bc6e6e63.png)

**Comment by dalbhanj** [comment]
Hi @AAber, these are really cool dashboards. Will you be able to send us a PR with these screenshots and some verbiage around it?
