### ISSUE TITLE
unable to open cloud9 from portal icon

### ISSUE THREAD

**Issue by geremyCohen** [aws-samples/eks-workshop#272]
STR:

1. Login with Hash at https://portal.awsworkshop.io/

2. Click on Console icon. Console opens. Close Console.
3. Click Cloud9 icon:

From web console:
Ready
(index):205 Clicked
(index):211 Object
(index):227 Got token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJnYW1lLWlkIjoiZGMzNmQ1NDU1M2JkNDVjNmIxMzE3ZWQ1NmE0Mzc1MmYiLCJ0ZWFtLWlkIjoiYjFiZGJmZDBkMGVjNDg0OWIyMDJhMmMyZGE4ZTA2ZjciLCJhdWQiOiIzZTA3MjgwY2Q0NjMiLCJpYXQiOjE1NTAwNjY3MzEuNzM4LCJleHAiOjE1NTAyMzk1MzEuNzM4fQ.dzoJig1GT0sTLNNfRSzcaxbr57pEMZAg9s1nQjC2-h0
(index):176 Clicked
(index):190 Clicked
(index):197 Uncaught TypeError: Cannot read property 'outputs' of undefined
    at Object.<anonymous> ((index):197)
    at u (jquery-3.3.1.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-3.3.1.min.js:2)
    at k (jquery-3.3.1.min.js:2)
    at XMLHttpRequest.<anonymous> (jquery-3.3.1.min.js:2)
(anonymous) @ (index):197
u @ jquery-3.3.1.min.js:2
fireWith @ jquery-3.3.1.min.js:2
k @ jquery-3.3.1.min.js:2
(anonymous) @ jquery-3.3.1.min.js:2
load (async)
send @ jquery-3.3.1.min.js:2
ajax @ jquery-3.3.1.min.js:2
(anonymous) @ (index):192
dispatch @ jquery-3.3.1.min.js:2
y.handle @ jquery-3.3.1.min.js:2

**Comment by geremyCohen** [comment]
Temp Workaround is to just run Cloud9 from us-west-2 (oregon region) from AWS Console Icon

**Comment by geremyCohen** [comment]
![aws_workshop_portal_and__161__amazon_chime](https://user-images.githubusercontent.com/1754064/52717779-16a7b900-2f5f-11e9-8e36-2c3c73b3664c.png)

Bug appears to be empty modules object.

**Comment by brentley** [comment]
I think this is caused by the event not being "started"
