### ISSUE TITLE
Use 'helm inspect values' to obtain 'values.yaml' in examples rather than curl

### ISSUE THREAD

**Issue by whereisaaron** [aws-samples/eks-workshop#280]
Lots of the great examples in the workshop using helm charts start with something like:
```
curl -o prometheus-values.yaml https://raw.githubusercontent.com/helm/charts/master/stable/prometheus/values.yaml
```
And then deploy using the chart. But the chart contains the `values.yaml` file and you can easily obtain it directly from the chart with:
```
helm inspect values stable/prometheus > prometheus-values.yaml 
```

**Comment by fmedery** [comment]
Hello, I do not see any mention of this type of command in the current version of the workshop.
Do not hesitate to reopen if needed
