### ISSUE TITLE
Amazon EKS Workshop > Tracing with X-Ray > Modify IAM Role command fix.

### ISSUE THREAD

**Issue by wongcyrus** [aws-samples/eks-workshop#283]
https://eksworkshop.com/x-ray/role/

The working command is

PROFILE=$(aws ec2 describe-instances --filters Name=tag:Name,Values=eksworkshop-eksctl-*-Node --query 'Reservations[0].Instances[0].IamInstanceProfile.Arn' --output text | cut -d '/' -f 2)

ROLE=$(aws iam get-instance-profile --instance-profile-name $PROFILE --query "InstanceProfile.Roles[0].RoleName" --output text)

aws iam attach-role-policy --role-name $ROLE --policy-arn arn:aws:iam::aws:policy/AWSXRayDaemonWriteAccess

**Comment by brentley** [comment]
I believe this has been addressed with a recent edit. Please reopen if it's still a problem.
