### ISSUE TITLE
add a step to execute screen command to mitigate eksctl failures due to loss of connection

### ISSUE THREAD

**Issue by geremyCohen** [aws-samples/eks-workshop#286]
We've seen in some rare occasions, users that lose access to the Cloud9 UI may also inadvertently lose access to the tty eksctl is running in.

Although the backend cloudformation scripts may continue to run, the CLI tool may lose state, resulting in a broken config.

To get around this, adding a step to run tmux or screen, then executing eksctl in that tty may help.

**Comment by brentley** [comment]
C9 is already in tmux. Are you saying that's not enough? Can't reconnect?

**Comment by geremyCohen** [comment]
I've seen the tty zombie away on reconnect in some cases.  Does that mean if it happens again we could do something similiar to a ```tmux ls``` and re-attach ?

**Comment by brentley** [comment]
Unknown, but it's worth testing. We should also possibly will this up to
the c9 team.

**Comment by brentley** [comment]
closing for now... let's reopen if it continues to be an issue.
