### ISSUE TITLE
cluster-autoscaler:v1.2.2 image is outdated in cluster_autoscaler.yml 

### ISSUE THREAD

**Issue by ismailyenigul** [aws-samples/eks-workshop#294]
Hi,

The image version used in 
ttps://eksworkshop.com/scaling/deploy_ca.files/cluster_autoscaler.yml is outdated.
`Image: gcr.io/google_containers/cluster-autoscaler:v1.2.2`
 
v.1.2.2 released on May 17, 2018.
Do you have a plan to update the latest one?

Thanks

**Comment by ismailyenigul** [comment]
Also, ASG name is not correct at  https://eksworkshop.com/scaling/deploy_ca/
ASG name in yaml file is eksctl-eksworkshop-eksctl-nodegroup-0-NodeGroup-SQG8QDVSR73G
but in AWS console screenshot it is ending with FLYO

**Comment by tdmalone** [comment]
According to https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler#releases, the version is dependant on the Kubernetes version, so this should probably be mentioned in the [instructions when editing the manifest](https://github.com/aws-samples/eks-workshop/blob/master/content/scaling/deploy_ca.md#configure-the-cluster-autoscaler).

**Comment by evisb** [comment]
Created PR #668, which resolves this problem by dynamically handling the assignment of CA image versions.

**Comment by fmedery** [comment]
PR merged #670 
Closing the issue.
Thank you @evisb
