### ISSUE TITLE
Question: contribution of the AWS Partner product

### ISSUE THREAD

**Issue by outcoldman** [aws-samples/eks-workshop#295]
Curious, if it is ok to contribute to the eks-workshop with the documentation on how to get the EKS logs to CloudWatch and S3/Glue with third party tool https://collectord.io
We (Outcold Solutions, company that built collectord) are AWS Technology Partner.

And this is a guidance on how to get the logs to S3/Glue and CloudWatch with Collectord https://collectord.io/blog/2019-03-13-aws-centralized-logging-for-kubernetes/

**Comment by brentley** [comment]
Yes, as long as there isn't a financial gate to using your platform... trial periods are fine.
