### ISSUE TITLE
Prometheus module - NodePort not working correctly

### ISSUE THREAD

**Issue by rnzsgh** [aws-samples/eks-workshop#297]
I believe the prometheus chart has been updated and the module is no longer working as expected. 

Chris H suggested the following:

```
kubectl create namespace prometheus
helm install stable/prometheus \ 
             --name prometheus \
             --namespace prometheus \
             --set alertmanager.persistentVolume.storageClass="gp2",server.persistentVolume.storageClass="gp2"
```

Instead of having to modify the security groups and lookup a single ip, you can access via port-forward:

```
kubectl port-forward -n prometheus deploy/prometheus-server 9090
```

This would allow us to remove the manual editing of prometheus-values.yaml and the creation of the custom storage class.

The URL then changes to: [http://localhost:9090/targets](http://localhost:9090/targets)

**Comment by christopherhein** [comment]
Only edit to this is the http://localhost:9090 from Cloud9 we need to change the `port-forward` to:

```
kubectl port-forward -n prometheus deploy/prometheus-server 8080:9090
```

And then instruct the user to **Preview Application**
