### ISSUE TITLE
cloud9's ec2 instance's role arn validity check instructions is ambiguous

### ISSUE THREAD

**Issue by geremyCohen** [aws-samples/eks-workshop#304]
From: https://eksworkshop.com/ee-support/prerequisites/workspaceiam/

Here are the conditions presented to the user.  They may be ambiguous, and should be narrowed down (or replaced with a script that can be run to return Good or Bad.)

* The role should contain:
eksworkshop-admin
or
TeamRole

* If the Arn contains the role name from above and an Instance ID
eg     "Arn": "arn:aws:sts::123456789012:assumed-role/TeamRole/i-01234567890abcdef"

* The role cannot contain (under Invalid heading):
If the _Arn contains TeamRole, MasterRole, or does not match the role name, DO NOT PROCEED. Go back and confirm the steps on this page.

That last condition says no TeamRole.  But the previous conditions said TeamRole is ok.

https://github.com/aws-samples/eks-workshop/pull/301

**Comment by brentley** [comment]
fixed
