### ISSUE TITLE
Test cluster

### ISSUE THREAD

**Issue by rajib76** [aws-samples/eks-workshop#312]
When I run the command to get the role name, I get two instance profile name. One may be an orphan name from a previous installation. Should the grep also contain the clustername+nodegroup?

aws iam list-instance-profiles | jq -r '.InstanceProfiles[].InstanceProfileName' | grep nodegroup                          

eksctl-eksworkshop-eksctl-nodegroup-ng-06fa9107-NodeInstanceProfile-FLBH701KYCAR
eksctl-eksworkshop-eksctl-rajib-V1-nodegroup-ng-4971c48c-NodeInstanceProfile-1R1JS01RJNNKZ

**Comment by brentley** [comment]
Yes this appears to be a bad setup in your account. The expectation is that
there is 1 eks cluster and 1 nodegroup in that region of the account.
