### ISSUE TITLE
add App Mesh service mesh chapter 

### ISSUE THREAD

**Issue by geremyCohen** [aws-samples/eks-workshop#314]
The version thats since been removed was compatible with the "preview" version of App Mesh.

 Now that we're in GA, create an App Mesh tutorial compatible with the release version.

**Comment by ChanceLee0111** [comment]
TeamRole given to cloud9 instance run by event engine doesn’t have permission of app mesh so hit error when run those commends at "Porting DJ to App Mesh -> Create the Mesh section"
aws appmesh list-meshes
aws appmesh describe-mesh --mesh-name dj-app

An error occurred (AccessDeniedException) when calling the ListMeshes operation: User: arn:aws:sts::446893124341:assumed-role/TeamRole/i-00d4439bdb5e0849d is not authorized to perform: appmesh:ListMeshes on resource: *

**Comment by geremyCohen** [comment]
Taking a look...

**Comment by geremyCohen** [comment]
This should be fixed now.  Please reopen if you find the same issue.
