### ISSUE TITLE
Deploy Prometheus Port Forward Error 8080 In use

### ISSUE THREAD

**Issue by jonahjon** [aws-samples/eks-workshop#325]
Received an error running the port-forward command for the prometheus module

`kubectl port-forward -n prometheus deploy/prometheus-server 8080:9090`

`Unable to listen on port 8080: All listeners failed to create with the following errors: Unable to create listener: Error listen tcp4 127.0.0.1:8080: bind: address already in use, Unable to create listener: Error listen tcp6 [::1]:8080: bind: address already in use
error: Unable to listen on any of the requested ports: [{8080 9090}]`

Running a diagnostic command showed me the port was still in Use

`lsof -w -n -i tcp:8080`

`kubectl 13866 ec2-user    3u  IPv6  64358      0t0  TCP *:webcache (LISTEN)`

**Comment by rnzsgh** [comment]
Hi Jonah,

Thanks for submitting this. Were you running the Dashboard port forwarder when you ran into this?

Ryan

**Comment by fmedery** [comment]
closing old issue, do not hesitate to reopen the issue if needed. 
thank yu
