### ISSUE TITLE
Helm init instructions (https://eksworkshop.com/helm/deploy/) fail

### ISSUE THREAD

**Issue by pcm32** [aws-samples/eks-workshop#328]
When using these instructions (https://eksworkshop.com/helm/deploy/) on a `eksctl` created cluster, init fails with:

```
Error: error installing: deployments.extensions is forbidden: User "system:anonymous" cannot create resource "deployments" in API group "extensions" in the namespace "kube-system"
```

Thanks!

**Comment by brentley** [comment]
Was this after adding the rbac.yml  to the cluster?

**Comment by fmedery** [comment]
`Helm` module has been update to V3. #661 

Don't hesitate to re open the issue if it still occurs.
