### ISSUE TITLE
app mesh control plane not syncing with crd controller

### ISSUE THREAD

**Issue by geremyCohen** [aws-samples/eks-workshop#340]
kubectl get of app mesh resources shows an app mesh config of mesh, VN, VS, but aws cli / console show only mesh.

crd controller logs show many errors: https://gist.githubusercontent.com/geremyCohen/055002df479cf7d304293a73e6ec7fce/raw/99f1801c6f139ac5ddbb3b3bfe0c47228e30a31b/gistfile1.txt

**Comment by fmedery** [comment]
Hello,
the App mesh has been updated.
Feel free to reopen the issue if needed.
