### ISSUE TITLE
Cluster Autoscaler does not have permissions to list replicasets.apps

### ISSUE THREAD

**Issue by ofaz** [aws-samples/eks-workshop#352]
When deploying the cluster autoscaler as per: https://eksworkshop.com/scaling/deploy_ca/, errors are generated suggesting that the cluster autoscaler cannot list replicasets.apps. I believe in some cases this also prevents any scale down or scale up activity from successfully occurring. 

The error logs take the form of:
`Failed to list *v1.ReplicaSet: replicasets.apps is forbidden: User "system:serviceaccount:kube-system:cluster-autoscaler"` 

A similar issue was found with other platforms deployments of the cluster autoscaler (e.g. https://github.com/Azure/aks-engine/issues/261) 

Is this expected / correct behaviour? I was able to address this by modifying the cluster-autoscaler.yaml at line 44 to include replicasets in its ClusterRole permissions. (https://github.com/aws-samples/eks-workshop/blob/master/content/scaling/deploy_ca.files/cluster_autoscaler.yml#L44) 

Happy to submit a PR if this is a confirmed issue!

**Comment by malz** [comment]
https://github.com/aws-samples/eks-workshop/blob/3ec6e6a0a033644527d1f022795208100b558ec9/content/scaling/deploy_ca.files/cluster_autoscaler.yml#L37-L39

It would appear that replicasets has been moved in apigroups from "extensions" (I believe when it was still in v1beta?) to "apps" permanently as of Kubernetes 1.14

See https://kubernetes.io/docs/setup/release/notes/#deprecations under API
>DaemonSet, Deployment, and ReplicaSet resources will no longer be served from extensions/v1beta1, apps/v1beta1, or apps/v1beta2 in v1.16. Migrate to the apps/v1 API, available since v1.9. Existing persisted data can be retrieved via the apps/v1 API.

**Comment by Jeffwan** [comment]
Permissions has been fixed in 

https://github.com/kubernetes/autoscaler/pull/2229
https://github.com/kubernetes/autoscaler/pull/2230
https://github.com/kubernetes/autoscaler/pull/2231

We can close this issue.

**Comment by malz** [comment]
Will the upstream fixes work if the user is following this tutorial? It would require an update to cluster autoscaler correct? Otherwise the solution posted above would fix it for this tutorial.

**Comment by Jeffwan** [comment]
Ah. I didn't notice that. Yeah. We need to submit a PR to this repo to use examples from CA aws examples.

**Comment by toricls** [comment]
I believe this should be fixed with https://github.com/aws-samples/eks-workshop/blob/master/content/beginner/080_scaling/deploy_ca.files/cluster_autoscaler.yml#L44
