### ISSUE TITLE
Fix webpage access for www.eksworkshop.com

### ISSUE THREAD

**Issue by deki** [aws-samples/eks-workshop#356]
Currently www.eksworkshop.com results in a 403 Error. The webpage is only accessible using http://eksworkshop.com (without www). As many folks are still typing www… please create a redirect to eksworkshop.com to avoid confusion. 
Already reported via email, creating this ticket as advised by @dalbhanj.

**Comment by fmedery** [comment]
Hello,
tX for the issue. You can track this erroe on #703
