### ISSUE TITLE
Log group not found -> /eks/eksworkshop-eksctl/containers

### ISSUE THREAD

**Issue by ORESoftware** [aws-samples/eks-workshop#357]
When I go to CloudWatch I get:

> Log group not found
> The log group /eks/eksworkshop-eksctl/containers could not be found. Check if it was correctly created and retry.

is that log group supposed to be created in the logging workshop?
https://eksworkshop.com/logging/

or maybe I need to do the eksctl workshop first?

**Comment by ONPEX** [comment]
Hi, just follow the example.
You need to have at least the cluster created. 

If you are using cloud9 editor, once you change the region and the cluster name, make sure you save your progress, deploy.
Go to the cloudwatch and you will see the /eks/eksworkshop-eksctl/containers

**Comment by fmedery** [comment]
Closing the issue. Don't hesitate to reopen if you still have the problem.
