### ISSUE TITLE
dial tcp 127.0.0.1:8080: connect: connection refused

### ISSUE THREAD

**Issue by ORESoftware** [aws-samples/eks-workshop#358]
I am getting this error:

> unable to recognize "/home/ec2-user/environment/fluentd/fluentd.yml": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused

which happens when I run on Cloud9:

`kubectl get pods -w --namespace=kube-system`

any idea why that is? sorry if this is a bad place to file a question

**Comment by tarek9900** [comment]
I would say your `$KUBECONFIG` file is "broken"  did you try to export it again? [see](https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/)

**Comment by fmedery** [comment]
Hello @ORESoftware 
It seems  your cluster is down  that the config you are using is not the correct one:

you can verify that the cluster is up with:
`eksctl get cluster`

eksctl creates a kubeconfig per cluster in `~/.kube/eksctl/clusters`

you get use one of these config by exporting  KUBECONFIG:
`export KUBECONFIG= ~/.kube/eksctl/clusters/CLUSTER`

or you get add the EKS config directly in ~/.kube/config :
`aws eks --region region-code update-kubeconfig --name cluster_name`
