### ISSUE TITLE
Add references to independent projects in each phase of App Mesh creation

### ISSUE THREAD

**Issue by geremyCohen** [aws-samples/eks-workshop#395]
During the App Mesh tutorial, the user executes scripts that may have been compiled from seperate repos.  This was done for simplifying the experience, but may lead users to look in one place for all components when building a mesh of their own [from scratch].

Add language in the chapters to make note of this, and call out the associated repo URLs.

**Comment by fmedery** [comment]
Hello,
App mesh lab has been updated and now use helm to install most components. 
Closing this issue for now
