### ISSUE TITLE
Bit confusion on Helm Instruction when replacing hard-coded values with template directives 

### ISSUE THREAD

**Issue by linuxus** [aws-samples/eks-workshop#399]
In the Helm instruction under the section "Replace hard-coded values with template directives" is using object notation and can be confused when searching string:

Example:
`spec.template.spec.containers.image` notation could be less confusing/ambiguous if it was notated as follow rather:
`spec:`
 `        containers:`
`                - image: `

First time I tried the workshop I was searching literal string instead of object notation.

**Comment by fmedery** [comment]
Hello, Thank you for the feedback
Helm lab has been updated to V3 #661
