### ISSUE TITLE
How to specify existing node security group in cloud formation template while creating EKS worker nodes

### ISSUE THREAD

**Issue by ArundathiGV** [aws-samples/eks-workshop#401]
I want to create worker nodes with an existing node security group in an EKS cluster. Currently, with the following cloudformation template, [a link](https://amazon-eks.s3-us-west-2.amazonaws.com/cloudformation/2019-02-11/amazon-eks-nodegroup.yaml, the EKS worker node is created with a new security group. How can I specify a pre-existing node security group for my worker nodes. Are there any cloud formation template with which I achieve this?

**Comment by oak2278** [comment]
@ArundathiGV - Check this template from the Spot Worker section. It creates new worker nodes with the existing SG. https://s3.amazonaws.com/eksworkshop.com/templates/master/amazon-eks-nodegroup-with-mixed-instances.yml

**Comment by BalzGuenat** [comment]
New location seems to be https://github.com/aws-samples/eks-workshop/blob/main/templates/amazon-eks-nodegroup-with-mixed-instances.yml
