### ISSUE TITLE
Latest version of EKSCTL breaks Role Exports

### ISSUE THREAD

**Issue by oak2278** [aws-samples/eks-workshop#402]
Cluster Export script located here (https://eksworkshop.com/eksctl/test/) does not work. Fails at 
STACK_NAME=$(eksctl get nodegroup --cluster eksworkshop-eksctl -o json | jq -r '.[].StackName')

EKSCTL Reference: https://github.com/weaveworks/eksctl/issues/1164

workaround: Create these exports manually using the Worker Node Role name and Instance Profile ARN of the Worker IAM role

**Comment by oak2278** [comment]
additional workaround: Add nodegroup name to the eksctl get node group command.

If you're following the instructions for an AWS event, the ng is predictable. Use the commands below
STACK_NAME=$(eksctl get nodegroup --cluster eksworkshop-eksctl  -n eksworkshop-ng1 -o json | jq -r '.[].StackName')
INSTANCE_PROFILE_ARN=$(aws cloudformation describe-stacks --stack-name $STACK_NAME | jq -r '.Stacks[].Outputs[] | select(.OutputKey=="InstanceProfileARN") | .OutputValue')
ROLE_NAME=$(aws cloudformation describe-stacks --stack-name $STACK_NAME | jq -r '.Stacks[].Outputs[] | select(.OutputKey=="InstanceRoleARN") | .OutputValue' | cut -f2 -d/)
echo "export ROLE_NAME=${ROLE_NAME}" >> ~/.bash_profile
echo "export INSTANCE_PROFILE_ARN=${INSTANCE_PROFILE_ARN}" >> ~/.bash_profile

If you're running the workshop in your own account, you can get the nodegroup name from the "eksctl.io/v1alpha2/nodegroup-name" tag on the CloudFormation template for the EKSCTL created node group. replace <NODEGROUP_NAME> in the example below

STACK_NAME=$(eksctl get nodegroup --cluster eksworkshop-eksctl  -n <NODEGROUP_NAME> -o json | jq -r '.[].StackName')
INSTANCE_PROFILE_ARN=$(aws cloudformation describe-stacks --stack-name $STACK_NAME | jq -r '.Stacks[].Outputs[] | select(.OutputKey=="InstanceProfileARN") | .OutputValue')
ROLE_NAME=$(aws cloudformation describe-stacks --stack-name $STACK_NAME | jq -r '.Stacks[].Outputs[] | select(.OutputKey=="InstanceRoleARN") | .OutputValue' | cut -f2 -d/)
echo "export ROLE_NAME=${ROLE_NAME}" >> ~/.bash_profile
echo "export INSTANCE_PROFILE_ARN=${INSTANCE_PROFILE_ARN}" >> ~/.bash_profile

**Comment by errordeveloper** [comment]
I'm working on this and we are aiming to release 0.4.2 with a fix later today.

**Comment by brentley** [comment]
> I'm working on this and we are aiming to release 0.4.2 with a fix later today.

awesome! I'm subscribed on the eksctl issue... I'll go back to latest once the fix is out.
