### ISSUE TITLE
Use eksctl config file instead of CLI to create the cluster

### ISSUE THREAD

**Issue by arun-gupta** [aws-samples/eks-workshop#410]
http://eksworkshop.com/eksctl/launcheks/#create-eks-cluster-1 uses the following command to create cluster in your own account:

```
eksctl create cluster --version=1.13 --name=eksworkshop-eksctl --nodes=3 --node-ami=auto --region=${AWS_REGION}
```

This should be moved to use a config file instead. Filing an issue for tracking purpose based upon the discussion in Chime

![image](https://user-images.githubusercontent.com/113947/63545502-6ce05080-c4dc-11e9-89ac-190f69fa051b.png)

**Comment by fmedery** [comment]
We are now using a YAML file to create the cluster. Thank you for the feedback
