### ISSUE TITLE
Review IAM Role Privileges

### ISSUE THREAD

**Issue by lucianommartins** [aws-samples/eks-workshop#421]
we should customize a role with the required privileges instead of giving AdminAccess (following security best practices on AWS)

**Comment by lucianommartins** [comment]
as talked with @arun-gupta

**Comment by arun-gupta** [comment]
@brentley this is again more workshop-wide issue, what do you recommend?

**Comment by psa-jforestier** [comment]
For the workshop, you could have the "AdminAccess" roles, but in the real-life, what are the minimum necessary role to use for example eksctl ? Maybe a reference to the full list of roles for this tool could be inserted.

**Comment by alberttwong** [comment]
Our company account doesn't allow that broad of permissions.  I need a minimal list of permissions.
