### ISSUE TITLE
Topics Flow

### ISSUE THREAD

**Issue by lucianommartins** [aws-samples/eks-workshop#422]
There are missing pointers on "Amazon EKS Workshop > Start the workshop... > ...at an AWS event" - the only link available, if the person running is not on a workshop/event, is "Start the workshop on your own".

But if the person already performed the tasks on "Start the workshop on your own", should be a link to the next steps (starting on "Amazon EKS Workshop > Start the workshop... > Install Kubernetes Tools").

**Comment by lucianommartins** [comment]
as talked with @arun-gupta

**Comment by arun-gupta** [comment]
@brentley this is more applicable for the overall workshop, not specific to Kubeflow
