### ISSUE TITLE
Show commands outputs

### ISSUE THREAD

**Issue by lucianommartins** [aws-samples/eks-workshop#423]
Add commands outputs/expected results for all times a command must be run.

Ie. looking on “Amazon EKS Workshop > Launch using eksctl > Prerequisites”, there is no expected/sample output for "eksctl version"

**Comment by lucianommartins** [comment]
as talked with @arun-gupta

**Comment by arun-gupta** [comment]
@brentley this is a more workspace-wide discussion. what's the legend here?
