### ISSUE TITLE
More details on CleanUp topic

### ISSUE THREAD

**Issue by lucianommartins** [aws-samples/eks-workshop#425]
Some further directions should be added to the "clean" section, ie. there are no directions to fully clean the environment (like deleting the cloudformation stacks).

It causes the following error when trying to delete the cluster (following the cleanup directions) and restart the workshop directions:
 
[✖]  creating CloudFormation stack "eksctl-eksworkshop-eksctl-cluster": AlreadyExistsException: Stack [eksctl-eksworkshop-eksctl-cluster] already exists
        status code: 400, request id: 2bbb9835-ca66-11e9-a28d-bda3da245ec8
[✖]  failed to create cluster "eksworkshop-eksctl"

**Comment by lucianommartins** [comment]
as talked with @arun-gupta

**Comment by arun-gupta** [comment]
@lucianommartins can you highlight which page needs to be cleaned up?

**Comment by otsuarez** [comment]
Hi, I believe this might be related to https://github.com/weaveworks/eksctl/issues/319#issuecomment-440940571

I had a similar problem, the cleanup instructions are good, the `--wait` option was the one thing I missed.
