### ISSUE TITLE
Docker image to be used on Machine Learning section

### ISSUE THREAD

**Issue by lucianommartins** [aws-samples/eks-workshop#426]
On "Amazon EKS Workshop > Machine Learning using Kubeflow > Jupyter Notebook", it is pointing to the tensorflow image that supports CPU only -- It should be pointing to the image with tensorflow:GPU, since this workshop section relies on a EC2 instance type with 4 NVIDIA V100 GPU devices.

**Comment by lucianommartins** [comment]
as talked with @arun-gupta

**Comment by arun-gupta** [comment]
@jeffwan even though we might choose a GPU-based image, Jupyter notebook still takes input as total amount of CPU. Do you see any value of choosing a GPU-based image?

**Comment by Jeffwan** [comment]
In the dropdown list, there's cpu and gpu images to choose. Arun, can you help update to use GPU resources? One more change is at the end of that page, you need to specify extended resource. 

CPU and memory will definitely be used for that GPU container.
