### ISSUE TITLE
jq not installed by default in Cloud9 environment

### ISSUE THREAD

**Issue by rizblie** [aws-samples/eks-workshop#441]
The page at `https://eksworkshop.com/prerequisites/workspaceiam/` contains the below CLI command sequence which uses `jq`

```
export ACCOUNT_ID=$(aws sts get-caller-identity --output text --query Account)
export AWS_REGION=$(curl -s 169.254.169.254/latest/dynamic/instance-identity/document | jq -r '.region')

echo "export ACCOUNT_ID=${ACCOUNT_ID}" >> ~/.bash_profile
echo "export AWS_REGION=${AWS_REGION}" >> ~/.bash_profile
aws configure set default.region ${AWS_REGION}
aws configure get default.region
```

However `jq` does not appear to be installed on Amazon Linux by default so the second line fails.

Suggested fix: instruct user to install `jq` by running
```sudo yum install jq```

**Comment by rizblie** [comment]
I note the instructions to install jq do appear later in the instructions - but this comes too late for the workspace setup.

**Comment by brentley** [comment]
Fixed... Will further reorder later today
