### ISSUE TITLE
No mention of VPC or subnet config needed

### ISSUE THREAD

**Issue by stevejalim** [aws-samples/eks-workshop#442]
On https://eksworkshop.com/prerequisites/workspace/ (source: master/content/prerequisites/workspace.md)  the instructions say

> * Select Create environment
> * Name it eksworkshop, and take all other defaults

However, brand new users will find there is no VPC to select, so one needs to be created. A nudge to help users here would be welcome, because VPC creation has lots of options - can they all just be left as defaults, too?

**Comment by stevejalim** [comment]
When I got to the page, the VPC and subnet drop-downs were in a red error state and no option was available for me to select, so I clicked the button to create a VPC and did so in a new tab, then refreshed the drop-down and it auto-populated with the just-created VPC.

Hope that helps. 

(I wish I'd screenshotted)

**Comment by stevejalim** [comment]
This may be related: note how the demo looks like it's using a public IP

<img width="631" alt="Screenshot 2019-09-10 at 15 10 20" src="https://user-images.githubusercontent.com/101457/64621301-5b081400-d3dd-11e9-8eb8-b07b90086719.png">

but when using the just-created-with-default-values VPC, I'm on a private IP 

<img width="772" alt="Screenshot 2019-09-10 at 15 10 32" src="https://user-images.githubusercontent.com/101457/64621287-50e61580-d3dd-11e9-8ee0-67524250257d.png">

**Comment by brentley** [comment]
172.31 is private also, and tends to be the range used in default vpcs. Can
you confirm whether or not you have a default vpc in your region?

**Comment by stevejalim** [comment]
Apols re missing the private IP.

The only VPC I have is the `eksworkshop` one I just created and this is now classed as default.

**Comment by brentley** [comment]
It sounds like you're working in a non standard account... Perhaps it's
corporate issued, and they strip out the default vpc?

**Comment by stevejalim** [comment]
It's certainly an IAM user under an organisation, rather than a 'personal' AWS account, so that might well be it.

**Comment by brentley** [comment]
Yeah. That makes sense.

**Comment by stevejalim** [comment]
Thanks, by the way, for the workshop - it's great

**Comment by brentley** [comment]
Awesome! Let me know if you run into any other issues.
