### ISSUE TITLE
Updating multiple cluster details in kubeconfig file

### ISSUE THREAD

**Issue by dhineshbabuelango** [aws-samples/eks-workshop#445]
Hi Team, Is there a way we can maintain multiple cluster details in single kubeconfig file, if so how can we call the respective clusters while running kubectl commands.

**Comment by fmedery** [comment]
Hello @dhineshbabuelango ,
Yes it is possible and most tools create new entries inside `~/.kube/config`
To manage theses entries I recommend https://github.com/ahmetb/kubectx/

`eksctl` creates a new kubeconfig file per cluster in ` ~/.kube/eksctl/clusters`
so yo just have to set `$KUBECONFIG`
