### ISSUE TITLE
Getting a 502 error with Kubernetes Dashboard.. Any Ideas?

### ISSUE THREAD

**Issue by ado120** [aws-samples/eks-workshop#447]
Hello all,

Following this workshop verbatim, however I am getting a 502 error when previewing the application with the Cloud9 IDE. No idea why this is happening even after destroying the cluster. Does anyone have any ideas?

**Comment by fmedery** [comment]
Hello,
I was unable to reproduce this behavior. Don't hesitate to reopen the issue if you still have the problem.
