### ISSUE TITLE
Machine Learning using Kubeflow - mysql pod fails to mount persistent volume

### ISSUE THREAD

**Issue by igeiman** [aws-samples/eks-workshop#449]
The  mysql and minio pods fail to get into Running state following the step:
kfctl apply all -V

It looks like the persistent volumes are allocated on CGE persisten disk.

Error message:
Warning  FailedMount  30m (x34 over 126m)   kubelet, ip-192-168-50-6.ec2.internal  Unable to mount volumes for pod "mysql-ffc889689-6lzmm_kubeflow(3fa34e36-df27-11e9-a1c8-0a79ec6f267e)": timeout expired waiting for volumes to attach or mount for pod "kubeflow"/"mysql-ffc889689-6lzmm". list of unmounted volumes=[mysql-persistent-storage]. list of unattached volumes=[mysql-persistent-storage default-token-2q8dc]

Looking at persistent volume it seems that is created with GCEPersistentDisk:
$ kubectl describe pv  mysql-pv -n kubeflow
Name:            mysql-pv
Labels:          <none>
Annotations:     pv.kubernetes.io/bound-by-controller: yes
Finalizers:      [kubernetes.io/pv-protection]
StorageClass:
Status:          Bound
Claim:           kubeflow/mysql-pv-claim
Reclaim Policy:  Retain
Access Modes:    RWO
VolumeMode:      Filesystem
Capacity:        20Gi
Node Affinity:   <none>
Message:
Source:
    Type:       GCEPersistentDisk (a Persistent Disk resource in Google Compute Engine)
    PDName:     dls-kf-storage-metadata-store
    FSType:     ext4
    Partition:  0
    ReadOnly:   false
Events:         <none>

Note: same issue with minio persistent volume.

$ kubectl get pv -n kubeflow
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                     STORAGECLASS   REASON   AGE
minio-pv                                   20Gi       RWO            Retain           Bound    kubeflow/minio-pv-claim                           173m
mysql-pv                                   20Gi       RWO            Retain           Bound    kubeflow/mysql-pv-claim                           173m
pvc-2c195134-df27-11e9-a1c8-0a79ec6f267e   10Gi       RWO            Delete           Bound    kubeflow/katib-mysql      gp2                     173m
pvc-32893b34-df27-11e9-a1c8-0a79ec6f267e   10Gi       RWO            Delete           Bound    kubeflow/metadata-mysql   gp2                     173m

$ vi kustomize/mysql/overlays/mysqlPd/persistent-volume.yaml

apiVersion: v1
kind: PersistentVolume
metadata:
  name: $(mysqlPvName)
spec:
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteOnce
  gcePersistentDisk:
    pdName: $(mysqlPd)
    fsType: ext4

**Comment by wdhorton** [comment]
@igeiman have you found a fix for this?
