### ISSUE TITLE
kubelet gets stuck in AWS EKS

### ISSUE THREAD

**Issue by dhineshbabuelango** [aws-samples/eks-workshop#451]
Hi All, While we are deploying our pod in kubernetes cluster, sometimes we see the below error when kubelet tries to pull the images from AWS ECR.

Warning  Failed     12m (x4 over 13m)     kubelet, ip-10-82-9-65.ap-XXXXX.compute.internal  Failed to pull image "XXXXXXXX.dkr.ecr.ap-XXXXXX.amazonaws.com/isam:9.0.7.0": rpc error: code = Unknown desc = Error response from daemon: Get https://XXXXXXX.dkr.ecr.ap-XXXXX.amazonaws.com/v2/ndi-spcp-isam/manifests/9.0.7.0: no basic auth credentials

When we restart kubelet, it is working fine. AWS support says, its issue with kubelet 

This is happening in EKS version 1.12, 1.13

**Comment by brentley** [comment]
What chapter is this from? Which instruction lead to this condition?

**Comment by fmedery** [comment]
Closing this issue.
@dhineshbabuelango do not hesitate to reopen the issue if you still have the problem.
