### ISSUE TITLE
Broken link in Service Mesh with Istio module

### ISSUE THREAD

**Issue by rizblie** [aws-samples/eks-workshop#456]
On the page at https://eksworkshop.com/servicemesh_with_istio/visualize/
there is a broken curl reference
curl -LO https://eksworkshop.com/servicemesh/deploy.files/istio-telemetry.yaml

which results in an AccessDenied error.

The correct curl command should be:
curl -LO https://eksworkshop.com/servicemesh_with_istio/deploy.files/istio-telemetry.yaml

**Comment by rizblie** [comment]
Further to the above, I don't think this manifest is actually required for the use case being demonstrated i.e. it is possible to use Prometheus and Grafana to verify that traffic is being split equally between two versions WITHOUT applying this manifest.

This manifest appears to be an (old) version of an example of how to add new metrics. However it has been superseded by other manifests in samples/bookinfo/telemetry.

**Comment by fmedery** [comment]
Hello,
`Istio` has been updated to 1.4.5 #667 
Closing this issue
