### ISSUE TITLE
Calico files return Access Denied

### ISSUE THREAD

**Issue by carlosafonso** [aws-samples/eks-workshop#463]
In the Calico section of the workshop (specifically https://eksworkshop.com/network-policies/calico/stars_policy_demo/apply_network_policies/), the guide instructs the user to fetch some files, such as `https://eksworkshop.com/calico/stars_policy_demo/apply_network_policies.files/default-deny.yaml`. When attempting to get them, the server returns a 403 error.

```
$ wget https://eksworkshop.com/calico/stars_policy_demo/apply_network_policies.files/default-deny.yaml
--2019-10-23 07:56:37--  https://eksworkshop.com/calico/stars_policy_demo/apply_network_policies.files/default-deny.yaml
Resolving eksworkshop.com (eksworkshop.com)... 99.86.122.64, 99.86.122.58, 99.86.122.9, ...
Connecting to eksworkshop.com (eksworkshop.com)|99.86.122.64|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2019-10-23 07:56:38 ERROR 403: Forbidden.
```

**Comment by FlorianOtel** [comment]
+1 the link provides a 403.  Same for the other files in the section for Calico network policies.

However, the files can be retried from the workshop GitHub repo here: 

https://github.com/aws-samples/eks-workshop/tree/master/content/beginner/120_network-policies/calico/stars_policy_demo/create_resources.files

**Comment by cornickj** [comment]
The path has changed to https://eksworkshop.com/beginner/120_network-policies/calico/stars_policy_demo and the content in https://github.com/aws-samples/eks-workshop/blob/master/content/beginner/120_network-policies/calico/stars_policy_demo/apply_network_policies.md needs updated.  

Probably in many more files to reflect the split into beginner/intermediate/advanced.
