### ISSUE TITLE
The log command given is wrong

### ISSUE THREAD

**Issue by gaurish** [aws-samples/eks-workshop#467]
Steps:

> $ eksctl create cluster --name=eksworkshop-eksctl --nodes=3 --alb-ingress-access --region=${AWS_REGION}
> [ℹ]  eksctl version 0.7.0
> [ℹ]  using region us-east-2
> [ℹ]  setting availability zones to [us-east-2b us-east-2a us-east-2c]
> [ℹ]  subnets for us-east-2b - public:192.168.0.0/19 private:192.168.96.0/19
> [ℹ]  subnets for us-east-2a - public:192.168.32.0/19 private:192.168.128.0/19
> [ℹ]  subnets for us-east-2c - public:192.168.64.0/19 private:192.168.160.0/19
> [ℹ]  nodegroup "ng-f5161675" will use "ami-082bb518441d3954c" [AmazonLinux2/1.14]
> [ℹ]  using Kubernetes version 1.14
> [ℹ]  creating EKS cluster "eksworkshop-eksctl" in "us-east-2" region
> [ℹ]  will create 2 separate CloudFormation stacks for cluster itself and the initial nodegroup
> [ℹ]  if you encounter any issues, check CloudFormation console or try '**eksctl utils describe-stacks --region=us-east-2 --name=eksworkshop-eksctl**'
> [ℹ]  CloudWatch logging will not be enabled for cluster "eksworkshop-eksctl" in "us-east-2"
> [ℹ]  you can enable it with 'eksctl utils update-cluster-logging --region=us-east-2 --name=eksworkshop-eksctl'
> [ℹ]  2 sequential tasks: { create cluster control plane "eksworkshop-eksctl", create nodegroup "ng-f5161675" }
> [ℹ]  building cluster stack "eksctl-eksworkshop-eksctl-cluster"
> [ℹ]  deploying stack "eksctl-eksworkshop-eksctl-cluster"
> [ℹ]  building nodegroup stack "eksctl-eksworkshop-eksctl-nodegroup-ng-f5161675"
> [ℹ]  --nodes-min=3 was set automatically for nodegroup ng-f5161675
> [ℹ]  --nodes-max=3 was set automatically for nodegroup ng-f5161675
> [ℹ]  deploying stack "eksctl-eksworkshop-eksctl-nodegroup-ng-f5161675"
> [✔]  all EKS cluster resources for "eksworkshop-eksctl" have been created
> [✔]  saved kubeconfig as "/home/ec2-user/.kube/config"
> [ℹ]  adding identity "arn:aws:iam::890162411770:role/eksctl-eksworkshop-eksctl-nodegro-NodeInstanceRole-8XEGYFULCZOS" to auth ConfigMap
> [ℹ]  nodegroup "ng-f5161675" has 0 node(s)
> [ℹ]  waiting for at least 3 node(s) to become ready in "ng-f5161675"

The above command in **BOLD** to view logs but when we try to run it, following happens:

```
$ eksctl utils update-cluster-logging --region=us-east-2 --name=eksworkshop-eksctl
[✖]  at least one flag has to be provided: --enable-types, --disable-types
```

**Comment by fmedery** [comment]
Hello, did you try with the latest version of `eksctl`?
If not, don't hesitate to open a issue with `eksctl` authors: https://github.com/weaveworks/eksctl
