### ISSUE TITLE
--force instead of -force

### ISSUE THREAD

**Issue by antpas** [aws-samples/eks-workshop#482]
https://eksworkshop.com/helm_root/helm_intro/install/

Once you install helm, the command will prompt you to run ‘helm init’. Do not run ‘helm init’. Follow the instructions to configure helm using Kubernetes RBAC and then install tiller as specified below If you accidentally run ‘helm init’, you can safely uninstall tiller by running ‘helm reset –force’

should be --force

**Comment by brentley** [comment]
thanks! this should be fixed now.
