### ISSUE TITLE
xray daemonset issue 

### ISSUE THREAD

**Issue by cc4i** [aws-samples/eks-workshop#523]
When try to run 
"kubectl create -f https://eksworkshop.com/x-ray/daemonset.files/xray-k8s-daemonset.yaml
"
following instructions at https://eksworkshop.com/x-ray/x-ray-daemon/,  got this error:

error: error validating "https://eksworkshop.com/x-ray/daemonset.files/xray-k8s-daemonset.yaml": error validating data: ValidationError(DaemonSet.spec): missing required field "selector" in io.k8s.api.apps.v1.DaemonSetSpec; if you choose to ignore these errors, turn validation off with --validate=false

Obviously it's something broken.

**Comment by cc4i** [comment]
Suggestion:
  following stuff was missed as per appVersion: apps/v1
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: xray-daemon
spec:
  updateStrategy:
    type: RollingUpdate

---
  **selector:
    matchLabels:
      app: xray-daemon**
---
  template:
    metadata:
      labels:
        app: xray-daemon
[xray-k8s-daemonset.yaml.zip](https://github.com/aws-samples/eks-workshop/files/3857049/xray-k8s-daemonset.yaml.zip)

I added those into manifest file and it works pretty well. Attached full file here.

**Comment by brentley** [comment]
I believe this was fixed with #533 ... thanks! please reopen if there is still a problem
