### ISSUE TITLE
App Mesh workshop update dj-app

### ISSUE THREAD

**Issue by kiranmeduri** [aws-samples/eks-workshop#535]
Current workshop documentation is stale and needs to be updated. It has some unsupported configuration that can lead to problems at runtime and hard to diagnose, see https://github.com/aws/aws-app-mesh-examples/issues/230. 

Workshop needs to be updated as per https://github.com/aws/aws-app-mesh-examples/blob/master/walkthroughs/eks/base.md, i.e. using helm.

**Comment by kiranmeduri** [comment]
@geremyCohen can you please guide us here. Thanks

**Comment by brentley** [comment]
@kiranmeduri can you provide specifics? we ran this workshop yesterday with success.

**Comment by kiranmeduri** [comment]
Workshop may succeed, but any subsequent actions on this appmesh installation may fail e.g. gRPC, TLS, retries. The reason being the CRDs and injector configurations are not up-to date and there is no easy way to update. 

We are still trying to debug if there is a bug in this specific workshop exercise. May be you can help the customer https://github.com/aws/aws-app-mesh-examples/issues/230

**Comment by kiranmeduri** [comment]
Specifically the image used by injector is old (v0.1.0) and does not have latest bug-fixes. Latest version if 0.3.0.

**Comment by kiranmeduri** [comment]
Any update on this? Thanks
