### ISSUE TITLE
note helm rbac prerequisites before installing metrics server

### ISSUE THREAD

**Issue by geremyCohen** [aws-samples/eks-workshop#56]
At https://eksworkshop.com/onug/scaling/deploy_hpa/#deploy-the-metrics-server if the RBAC for helm is not setup correctly first per https://eksworkshop.com/onug/helm/deploy/ the metrics server install will fail.

```helm reset``` then ```helm init``` is a way to recover if you installed helm before applying these correct RBAC settings.

**Comment by fmedery** [comment]
Helm Lab has been updated to V3. #661 #665 #662 
Closing this issue
