### ISSUE TITLE
codepipeline build is broken

### ISSUE THREAD

**Issue by geremyCohen** [aws-samples/eks-workshop#583]
When running the setup here: https://eksworkshop.com/intermediate/220_codepipeline/codepipeline/

Upon the CF Template completing, I switch to Oregon for CodePipeline, and the build status is failed.  Log of CodePipeline build log here: https://gist.github.com/geremyCohen/e925a375714c6f79c1dd8d804faa2005

**Comment by geremyCohen** [comment]
Could this have anything to do with running the SA for Pods chapter just before?

**Comment by geremyCohen** [comment]
Error appears here:  

```
[Container] 2019/11/28 02:27:59 Running command kubectl apply -f hello-k8s.yml 
error: SchemaError(io.k8s.api.extensions.v1beta1.PodSecurityPolicy): invalid object doesn't have additional properties 
 
[Container] 2019/11/28 02:28:00 Command did not exit successfully kubectl apply -f hello-k8s.yml exit status 1 
```

**Comment by gfediere** [comment]
HI @geremyCohen According to your error log, this seems to be a pod security policy issue so maybe linked to the SA module.
I get the same kind of errror: 
```
error: SchemaError(io.k8s.api.coordination.v1.LeaseList): invalid object doesn't have additional properties 
```
I solved it by replacing the kubectl version in the .buildspec.yml
Form:
```
https://amazon-eks.s3-us-west-2.amazonaws.com/1.10.3/2018-07-26/bin/linux/amd64/kubectl
```
To: 
```
https://amazon-eks.s3-us-west-2.amazonaws.com/1.14.6/2019-08-22/bin/linux/amd64/kubectl
```
Don't know if this could help

**Comment by geremyCohen** [comment]
Thanks so much for narrowing that down @gfediere !  I've verified it, and submitted a PR.
