### ISSUE TITLE
module Using Spot Instances with EKS fail to get INSTANCE_PROFILE_ARN

### ISSUE THREAD

**Issue by gfediere** [aws-samples/eks-workshop#587]
Hi.
In this module, we need to deploy a CF template with the INSTANCE_PROFILE_ARN. But according to the commit #563, INSTANCE_PROFILE_ARN is not defined anymore.

**Comment by fmedery** [comment]
Hello,
Just to let you know that we updated the lab to use `eksctl` instead of cloudformation and so INSTANCE_PROFILE_ARN is not needed anymore
