### ISSUE TITLE
add key parameter to eksctl cluster create command

### ISSUE THREAD

**Issue by geremywork** [aws-samples/eks-workshop#618]
We create an SSH keypair, upload it to AWS, but do not bootstrap the cluster with it.  To be able to utilize this as the login key to the instances, per the EKSCTL docs:

```
To use a pre-existing EC2 key pair in us-east-1 region, you can specify key pair name (which must not resolve to a local file path), e.g. to use my_kubernetes_key run:

eksctl create cluster --ssh-access --ssh-public-key=my_kubernetes_k
```

**Comment by fmedery** [comment]
Hello.
Thank you for the issue.
It is not mandatory `~/.ssh/id_rsa.pub` is the default:
```golang
ng.SSH.Allow = fs.Bool("ssh-access", *ng.SSH.Allow, "control SSH access for nodes. Uses ~/.ssh/id_rsa.pub as default key path if enabled")
```
[code reference](https://github.com/weaveworks/eksctl/blob/91b49c90bf526da7a358b19c36b527cbb4e36fa6/pkg/ctl/cmdutils/nodegroup_flags.go#L38)
