### ISSUE TITLE
Cluster Autoscaler definition is not correct

### ISSUE THREAD

**Issue by fmmasood** [aws-samples/eks-workshop#621]
content/beginner/080_scaling/_index.md

Please update CA definition  
Current: Cluster Autoscaler (CA) is the default K8s component that can be used to perform pod scaling as well as scaling nodes in a cluster. 

CA cant scale pods only nodes.

**Comment by cfregly** [comment]
And CA can only scale nodes in a single AZ.  This can affect how the user initially sets up the EKS cluster.

**Comment by brentley** [comment]
Thanks for the input! I'd love to get your take on how better to
phrase it... can you click "edit this page" and submit a pull request with
your updated language?
--------
Brent
--------
