### ISSUE TITLE
Your yml file in sample is too old

### ISSUE THREAD

**Issue by tony-Ma-yami** [aws-samples/eks-workshop#640]
Page : https://eksworkshop.com/advanced/310_servicemesh_with_istio/visualize/

Your file  : https://eksworkshop.com/advanced/310_servicemesh_with_istio/deploy.files/istio-telemetry.yaml

Correction : 
![image](https://user-images.githubusercontent.com/42396612/72309659-8fa51880-36ba-11ea-8eaa-5045ccbe3a5b.png)

**Comment by fmedery** [comment]
Hello,
Thank you for the feedback, `Istio` has been updated #667
