### ISSUE TITLE
Any plans to support i18n?

### ISSUE THREAD

**Issue by yhware** [aws-samples/eks-workshop#641]
Our team is in the process of moving our architecture to k8s but there's the language barrier making the process slower.

I'd be happy to contribute Korean translation if you guys are up to it.

**Comment by brentley** [comment]
We'd love to!

**Comment by yhware** [comment]
Perfect :) So how would I go about doing this though? 
In honesty, I'd rather not mess with the whole site's configuration (i.e. add i18n button, features etc) and simply focus on the translation itself.

All I can imagine is forking this repo and overwriting it with Korean but that doesn't seem to be the way to go about it.

If the first method is required, any guidance would be appreciated.

**Comment by yhware** [comment]
Actually, just found out hugo supports i18n quite nicely according to this post - https://phrase.com/blog/posts/i18n-tutorial-how-to-go-multilingual-with-hugo/
but it requires the directories be changed to

/content/english/010_introduction/...
/content/korean/010_introduction/...

from the current /content/010_introduction/...

would you be open to this sort of change in directory structure?

**Comment by brentley** [comment]
I believe we can also change the file extension from filename.md to
filename.en.md or the equivalent for the other supported languages.

If you want to start in that direction, and open a WIP pull request, I'll
help with modding the config.

**Comment by yhware** [comment]
That sounds even better. Thanks for the help :)
