### ISSUE TITLE
Update workshop to use Helm 3.X

### ISSUE THREAD

**Issue by umairishaq** [aws-samples/eks-workshop#645]
With the release of Helm 3.0, back in November 2019, the workshop needs to be updated to use Helm 3.X. As this major update includes security related features, the update to workshop would help with the adoption of Helm 3.X.

**Comment by fmedery** [comment]
Thank you for the feedback we are in the process of updating the workshop to use V3

**Comment by otterley** [comment]
Resolved by #661 and #662
