### ISSUE TITLE
Example Polices are too wide

### ISSUE THREAD

**Issue by belialboy** [aws-samples/eks-workshop#656]
In the "Create an IAM role for your Workspace" and "Create and AWS account" pages students are asked to use the AdministratorAccess policy. The user nor C9 role need not be that wide, and this potentially leaves their account unnecessarily open to priv escalation and other abuse. Let's fix that.

**Comment by alberttwong** [comment]
I would add is that our company account doesn't allow AdministratorAccess.  We need a minimal list of permissions.
