### ISSUE TITLE
clarify that we're going to save a file and then open it and edit it.

### ISSUE THREAD

**Issue by geremyCohen** [aws-samples/eks-workshop#68]
https://eksworkshop.com/integration/monitoring/deploy-prometheus/

Change: 
```curl -o prometheus-values.yaml https://raw.githubusercontent.com/helm/charts/master/stable/prometheus/values.yaml```

> Search for # storageClass: “-”, uncomment and change the value to “prometheus”. You will do this twice, under both server & alertmanager manifests

to something like:

To install Prometheus, first we'll download the Prometheus configuration using curl, then edit the storageClass attribute.

To download the configuration as values.yaml, execute the following command:

```curl -o prometheus-values.yaml https://raw.githubusercontent.com/helm/charts/master/stable/prometheus/values.yaml```

> Next, using a text editor, open up values.yaml, search for ```# storageClass: “-”```, uncomment and change the value to “prometheus”. You will do this twice, under both server & alertmanager manifests

**Comment by fmedery** [comment]
Closing the issue.
Lab has been updated since the issue was opened.
