### ISSUE TITLE
Recommend to add instruction/comment if have existing aws-auth ConfigMap in section - MAP AN IAM USER TO K8S

### ISSUE THREAD

**Issue by 0xlen** [aws-samples/eks-workshop#681]
In the tutorial: https://eksworkshop.com/beginner/090_rbac/map_iam_user_to_k8s_user/

It only mentioned to apply `aws-auth` ConfigMap directly. It would be great if can suggest users can do edit(`kubectl edit -n kube-system configmap/aws-auth`) if they already have one [1]. The action can cause issue for some use cases, for example:

- User already have existing `aws-auth` ConfigMap due to eksctl already created for them
- User launch managed NodeGroup, EKS will help to add them to the aws-auth ConfigMap. This action will replace existing ConfigMap and cause Nodes become `NotReady`.

[1] Managing Users or IAM Roles for your Cluster - https://docs.aws.amazon.com/en_us/eks/latest/userguide/add-user-role.html

**Comment by awsandy** [comment]
Agree 

It would be better to get the existing config map - then append the rbac-user
This worked for me:

kubectl get configmap -n kube-system aws-auth -o yaml > aws-auth.yaml
cat << EoF >> aws-auth.yaml
data:
  mapUsers: |
    - userarn: arn:aws:iam::${ACCOUNT_ID}:user/rbac-user
      username: rbac-user
EoF
kubectl apply -f aws-auth.yaml

**Comment by awsandy** [comment]
(with the required spaces in the yaml of course !)

**Comment by awsandy** [comment]
Put a PR in 
https://github.com/aws-samples/eks-workshop/pull/796
