### ISSUE TITLE
port-forward may fail if pods have not come up yet

### ISSUE THREAD

**Issue by geremyCohen** [aws-samples/eks-workshop#72]
https://eksworkshop.com/integration/monitoring/deploy-prometheus/

After 

```
export POD_NAME=$(kubectl get pods --namespace prometheus -l "app=prometheus,component=server" -o jsonpath="{.items[0].metadata.name}")

kubectl --namespace prometheus port-forward $POD_NAME 9090

```

We may want to add something like:

If you get an error similar to ```error: unable to forward port because pod is not running. Current status=Pending```  the Prometheus pods may just not had a chance to come up yet.  If you get this error, wait 30s, and retry the command.

**Comment by fmedery** [comment]
closing the bug. the command above is not used anymore.
Tx
