### ISSUE TITLE
Unable to use kubectl with the EKS cluster...aws: error: argument operation: Invalid choice...

### ISSUE THREAD

**Issue by trevorrobertsjr** [aws-samples/eks-workshop#734]
# Problem
Users may see text similar to the title of this issue when using Cloud9 workspaces created on or after March 23, 2020 (The EKS Workshop Team is working with the Cloud9 team on this).

The problem is related to an outdated version of the AWS CLI being included in the Cloud9 instance AMI.

You can verify which AWS CLI version you have with the following command:
`aws --version`

You need to have AWS CLI version 1.18.15, or higher, to successfully run the EKS Workshop.

# Resolution
## Update AWS CLI
```
sudo yum remove -y aws-cli
pip3 install --user awscli
sudo ln -s $HOME/.local/bin/aws /usr/bin/aws
```

## Run The kubectl Configuration Commands
```
aws eks get-token --cluster-name your-cluster-name
aws eks update-kubeconfig --name your-cluster-name
```

**Comment by trevorrobertsjr** [comment]
We will keep this issue open until we verify new Cloud9 workspaces have the correct AWS CLI version.

**Comment by joebowbeer** [comment]
Note that update instructions in the workshop do not match those in this issue's description.

https://eksworkshop.com/020_prerequisites/k8stools/#update-awscli

**Comment by brentley** [comment]
fixed in bd8f534

**Comment by trevorrobertsjr** [comment]
@joebowbeer Thank you for confirming. I posted these instructions before the workshop instructions had been updated.

Both sets of instructions work. However, the update instructions in the workshop require the attendee to refresh the terminal.

**Comment by brentley** [comment]
I've added a refresh command to the instructions.
--------
Brent
--------

**Comment by limeniye** [comment]
![зображення](https://user-images.githubusercontent.com/69314237/227314609-6db8b38c-3b0e-4c76-b45d-c69d22611c2d.png)

```
2023-03-23 20:34:16 [✖]  unable to use kubectl with the EKS cluster (check 'kubectl version'): WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Unable to connect to the server: getting credentials: decoding stdout: couldn't get version/kind; json parse error: json: cannot unmarshal string into Go value of type struct { APIVersion string "json:\"apiVersion,omitempty\""; Kind string "json:\"kind,omitempty\"" }
```

>kubectl version
```
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:36:36Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"windows/amd64"}
Kustomize Version: v4.5.7
Unable to connect to the server: getting credentials: decoding stdout: couldn't get version/kind; json parse error: json: cannot unmarshal string into Go value of type struct { APIVersion string "json:\"apiVersion,omitempty\""; Kind string "json:\"kind,omitempty\"" }
```

**Comment by AdeOsinloyeJr** [comment]
Also having the same issue, were you able to resolve?
