### ISSUE TITLE
Token request for Kubernetes dashboard fails using aws eks get-token

### ISSUE THREAD

**Issue by BenFields724** [aws-samples/eks-workshop#740]
eksworkshop is configured to use aws-iam-authenticator and the screenshot shown to get the dashboard login token even uses the aws-iam-authenticator command, but the command shown is still aws eks get-token. Needs to be updated to reflect the use of aws-iam-authenticator.

**Comment by otterley** [comment]
`aws eks get-token` uses aws-iam-authenticator under the hood.  Why do you believe that this needs to be changed?  Is something broken?

**Comment by BenFields724** [comment]
Call fails with current command and the screenshot shown is even using the aws-iam-authenticator command so not sure when this happened, but something must be broken. @otterley

**Comment by BenFields724** [comment]
Issue addressed in commit 8c074fa. Install now uses an updated aws-cli version that allows the aws eks get-token command.
