### ISSUE TITLE
Proxy port broken after updating K8s Dashboard

### ISSUE THREAD

**Issue by brunomedbar** [aws-samples/eks-workshop#789]
Hi,

Thanks for updating the k8s dashboard to the latest version. I'm just testing it and it seems that Cloud9 requires kubectl proxy to still listen on port 8080 (instead of 8001, as suggested in the change made in the commit [`42ba607`](https://github.com/aws-samples/eks-workshop/commit/42ba607bdcad6df33ad2996d731b846eed8800d5). 

Could you please confirm that or should I perform any additional configuration to run the workshop using port 8001?

Thanks in advance.

**Comment by fmedery** [comment]
Thank you for the report, the port should be 8080 the lab has been updated: #792
