### ISSUE TITLE
kubectl run php-apache not creating Deployment

### ISSUE THREAD

**Issue by shaimona** [aws-samples/eks-workshop#794]
When running the command `kubectl run php-apache --image=us.gcr.io/k8s-artifacts-prod/hpa-example --requests=cpu=200m --expose --port=80` it is only creating service and pod. Not Deployment. 
➜ kubectl run php-apache --image=us.gcr.io/k8s-artifacts-prod/hpa-example --restart=Always --requests=cpu=200m --expose --port=80
service/php-apache created
pod/php-apache created

**Comment by cgrothaus** [comment]
This affects the _"SCALE AN APPLICATION WITH HPA"_ lesson in `080_scaling/test_hpa`. As stated above, `kubectl run php-apache ...` does **not** create a _deployment_, so the next step in the lesson, `kubectl autoscale deployment php-apache ...`, fails.

**Comment by brentley** [comment]
When I run:
```
kubectl run php-apache --image=us.gcr.io/k8s-artifacts-prod/hpa-example --requests=cpu=200m --expose --port=80
```
I can then see a deployment:
```
$ kubectl get deployments
NAME             READY   UP-TO-DATE   AVAILABLE   AGE
load-generator   1/1     1            1           67s
php-apache       1/1     1            1           111s
```
also, running the command:
```
kubectl autoscale deployment php-apache --cpu-percent=50 --min=1 --max=10
```
works for me. 

Can you give more details about your environment/setup and how it might be different from the one we build in the workshop?

**Comment by brentley** [comment]
I suspect the difference might be in the version of kubectl you're using and the version the workshop expects you to use.

This is what I have installed:
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.10-eks-bac369", GitCommit:"bac3690554985327ae4d13e42169e8b1c2f37226", GitTreeState:"clean", BuildDate:"2020-02-21T23:37:18Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-eks-e16311", GitCommit:"e163110a04dcb2f39c3325af96d019b4925419eb", GitTreeState:"clean", BuildDate:"2020-03-27T22:37:12Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}```

I'll try updating to your version and see if that makes a difference.

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-eks-e16311", GitCommit:"e163110a04dcb2f39c3325af96d019b4925419eb", GitTreeState:"clean", BuildDate:"2020-03-27T22:37:12Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

Now we're on the same version. I'll try the command again:

```
$ kubectl run php-apache --image=us.gcr.io/k8s-artifacts-prod/hpa-example --requests=cpu=200m --expose --port=80
service/php-apache created
pod/php-apache created
```

Yep. It looks like the incorrect kubectl version is causing this issue. Would you mind confirming by installing the version specified in the workshop and trying again?

**Comment by cgrothaus** [comment]
Confirmed. I tried the _EKS vended kubectl version_ found at https://docs.aws.amazon.com/eks/latest/userguide/install-kubectl.html for version `v1.16.8-eks-e16311` as well as for version `v1.15.10-eks-bac369`. Both create a _service_ and a _deployment_ 🎉 .

So it is the non-EKS vended kubectl version `v1.18.3` that makes the difference here.

**Comment by NicolaivdSmagt** [comment]
[kubectl 1.18 doesn’t create deployments anymore, but pods.](https://medium.com/p/2a88e5fb389a/) This will require an update to the workshop, as this functionality is not coming back.

**Comment by brentley** [comment]
Yeah. We'll have to find an alternative. For now, I'll leave this issue open to track the future change.

**Comment by fmedery** [comment]
based on reading, if we do not want to create YAML file to replace each `kubernetes run` we could replace command like:
```bash
kubectl run php-apache \
  --image=us.gcr.io/k8s-artifacts-prod/hpa-example \
  --requests=cpu=200m \
  --expose \
  --port=80
```
by
```bash
kubectl create deployment php-apache --image=us.gcr.io/k8s-artifacts-prod/hpa-example 
kubectl set resources deployment.apps/php-apache --requests=cpu=200m
kubectl expose deployment.apps/php-apache --port 80
```


it is from 1 liner to 3 commands but they are really easy to read and understand compare to creating a YAML file.

I can help with updating the labs
