### ISSUE TITLE
Token Sign In not working

### ISSUE THREAD

**Issue by josjaf** [aws-samples/eks-workshop#803]
Hello,

I'm on this step: https://eksworkshop.com/beginner/040_dashboard/connect/

and when I get the token and paste it into the Token field for Kuberenetes Dashboard, the signin button doesn't do anything. 

I also get this message on some of the button clicks in the cloud 9 environment:
`I0528 18:51:15.025397    5811 log.go:172] http: proxy error: context canceled`

When I try to hit the url outside of Cloud9, I get http 431 errors.

**Comment by jwoehrle** [comment]
I can confirm this... the log of the dashboard pod seems fine:

> 2020/05/29 12:28:45 [2020-05-29T12:28:45Z] Incoming HTTP/2.0 GET /api/v1/csrftoken/login request from 192.168.143.38:53160: { contents hidden }
> 2020/05/29 12:28:45 [2020-05-29T12:28:45Z] Outcoming response to 192.168.143.38:53160 with 200 status code
> 2020/05/29 12:28:45 [2020-05-29T12:28:45Z] Incoming HTTP/2.0 POST /api/v1/login request from 192.168.143.38:53160: { contents hidden }
> 2020/05/29 12:28:45 [2020-05-29T12:28:45Z] Outcoming response to 192.168.143.38:53160 with 200 status code
> 2020/05/29 12:28:45 [2020-05-29T12:28:45Z] Incoming HTTP/2.0 GET /api/v1/plugin/config request from 192.168.143.38:53160: 
> 2020/05/29 12:28:45 [2020-05-29T12:28:45Z] Outcoming response to 192.168.143.38:53160 with 200 status code
> 2020/05/29 12:28:45 [2020-05-29T12:28:45Z] Incoming HTTP/2.0 GET /api/v1/login/status request from 192.168.143.38:53160: 
> 2020/05/29 12:28:45 [2020-05-29T12:28:45Z] Outcoming response to 192.168.143.38:53160 with 200 status code
> 2020/05/29 12:28:45 [2020-05-29T12:28:45Z] Incoming HTTP/2.0 GET /api/v1/login/status request from 192.168.143.38:53160: 
> 2020/05/29 12:28:45 [2020-05-29T12:28:45Z] Outcoming response to 192.168.143.38:53160 with 200 status code
> 2020/05/29 12:28:45 [2020-05-29T12:28:45Z] Incoming HTTP/2.0 GET /api/v1/login/status request from 192.168.143.38:53160: 
> 2020/05/29 12:28:45 [2020-05-29T12:28:45Z] Outcoming response to 192.168.143.38:53160 with 200 status code

Firefox console log says:

> Some cookies are misusing the recommended “sameSite“ attribute 5
> Cookie “AWSALB” will be soon rejected because it has the “sameSite” attribute set to “none” or an invalid value, without the “secure” attribute. To know more about the “sameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Cookies

Sometime when I remove the tripple `/` in the URL I can get to the dashboard main page, however with the error message:

![image](https://user-images.githubusercontent.com/14852794/83260220-af486380-a1b9-11ea-8c20-11106005b004.png)

**Comment by brentley** [comment]
I notice that using the built-in cloud9 preview browser doesn't work, but when I open the preview in a new browser tab (using chrome) the token auth does work.

**Comment by dgomesbr** [comment]
Hey @brentley happening right now on a live immersion day. Even with a new chrome window

**Comment by ignaciofuentes** [comment]
I just ran into this issue as well.
Switching from Chrome to Firefox solved it for me.

**Comment by ysam12345** [comment]
Ran into this issue as well. Using Firefox to open the url is work for me.
