### ISSUE TITLE
CA Scaling Error

### ISSUE THREAD

**Issue by josjaf** [aws-samples/eks-workshop#806]
Error on this page:

https://eksworkshop.com/beginner/080_scaling/test_ca/

k8s.io/client-go/informers/factory.go:134: Failed to list *v1beta1.CSINode: csinodes.storage.k8s.io is forbidden: User "system:serviceaccount:kube-system:cluster-autoscaler" cannot list resource "csinodes" in API group "storage.k8s.io" at the cluster scope

Is this to be expected?

**Comment by brentley** [comment]
which command triggered this error? was it?: 
```
kubectl scale --replicas=10 deployment/nginx-to-scaleout
```

**Comment by josjaf** [comment]
`kubectl logs -f deployment/cluster-autoscaler -n kube-system`

so, yes this did it `kubectl scale --replicas=10 deployment/nginx-to-scaleout`
