### ISSUE TITLE
eks-workshop/content/advanced/410_batch

### ISSUE THREAD

**Issue by manishdhawaria** [aws-samples/eks-workshop#820]
Deprecated APIs Removed In 1.16 - (Deployment in the extensions/v1beta1, apps/v1beta1, and apps/v1beta2 API versions is no longer served
Migrate to use the apps/v1 API version, available since v1.9. Existing persisted data can be retrieved/updated via the new version.)

to be used v2.8.2
https://raw.githubusercontent.com/argoproj/argo/v2.8.2/manifests/install.yaml

**Comment by fmedery** [comment]
thang for reporting this issue. We updated the lab to the latest version argo:  #864
