### ISSUE TITLE
Use IRSA for Fluentd service account / EKS Best practices

### ISSUE THREAD

**Issue by rafaelpereyra** [aws-samples/eks-workshop#867]
The best practices for EKS cluster is being [published](https://aws.github.io/aws-eks-best-practices/iam/) recently and the use of the Instance IAM is not recommended in benefit of using IRSA:

> Restrict access to the instance profile assigned to the worker node
When you use IRSA, the Pod no longer inherits the rights of the instance profile assigned to the worker node. Nonetheless, as an added precaution, you may want to block a process's ability to access instance metadata. This will effectively prevent pods that do not use IRSA from inheriting the role assigned to the worker node. Be aware that when you block access to instance metadata on a worker node, it may prevent certain pods from functioning properly. For additional information about how to block access to instance metadata, see https://docs.aws.amazon.com/eks/latest/userguide/restrict-ec2-credential-access.html.

The approach of adding the policy to the worker node role [here](https://www.eksworkshop.com/intermediate/230_logging/prereqs/) contradicts this best practice.

The recommended approach should be adding the policy to an IAM role for fluentd and then decorate the service account "fluentd" with the proper ARN.

**Comment by fmedery** [comment]
Thank you for the report. We updated the lab to use IRSA and the latest version of fluent bit.
