### ISSUE TITLE
Error with Auto scaling - https://www.eksworkshop.com/beginner/080_scaling/deploy_ca/

### ISSUE THREAD

**Issue by sbpath** [aws-samples/eks-workshop#879]
Looks to be permission issue with v1.17 and https://eksworkshop.com/beginner/080_scaling/deploy_ca.files/cluster_autoscaler.yml
I have to add below patch to clusterrole to fix the issue.

# cat cluster_autoscaler.yml.patch 
--- cluster_autoscaler.yml      2020-06-19 19:37:37.000000000 +0000
+++ cluster_autoscaler.yml.1    2020-07-21 02:05:00.000000000 +0000
@@ -49,6 +49,9 @@
 - apiGroups: ["batch","extensions"]
   resources: ["jobs"]
   verbs: ["watch","list","get","patch"]
+- apiGroups: ["coordination.k8s.io"]
+  resources: ["leases"]
+  verbs: ["watch","list","get","patch","create","update"]
 
 ---
 apiVersion: rbac.authorization.k8s.io/v1beta1

Logs below:
I0721 01:21:11.711812       1 leaderelection.go:247] failed to acquire lease kube-system/cluster-autoscaler
E0721 01:21:15.164237       1 leaderelection.go:331] error retrieving resource lock kube-system/cluster-autoscaler: leases.coordination.k8s.io "cluster-autoscaler" is forbidden: User "system:serviceaccount:kube-system:cluster-autoscaler" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "kube-system"

**Comment by fmedery** [comment]
lab has been updated. thank you for reporting it
