### ISSUE TITLE
Cluster Autoscaler content needs refresh

### ISSUE THREAD

**Issue by otterley** [aws-samples/eks-workshop#890]
The current instructions for installing Cluster Autoscaler are quite outdated at this point. Let's switch to installing CA via the stable Helm chart.

**Comment by ruecarlo** [comment]
I'd suggest also we pick some of the content/examples we have in the Spot EKS workshop for this.  Personally I think the addition we have done in the Spot workshop to add kube-ops-view to provide visual aid of scaling + the flow of the testing and extra exercises would make for a good addition; Happy to contribute that part and sync up both workshop on that part.  Would like to hear thoughts in that regard.

**Comment by otterley** [comment]
@ruecarlo Can you create a new issue for this? Otherwise we can't close this issue solely by updating the installation instructions.

**Comment by ruecarlo** [comment]
Fair point. Will do.

**Comment by fmedery** [comment]
@otterley I can take care of the AC update before the end of the week

**Comment by aharontwizer** [comment]
@otterley @ruecarlo  - I created a new issue for Kube-ops-view: https://github.com/aws-samples/eks-workshop/issues/948

**Comment by htroisi** [comment]
The [Configure Cluster Autoscaler (CA)](https://www.eksworkshop.com/beginner/080_scaling/deploy_ca/) workshop is not working as expected for me. Many of the pods remain in the Pending state:

![image](https://user-images.githubusercontent.com/66266496/111254631-b4549300-85d2-11eb-8497-1f79c2d03707.png)

The cluster-autoscaler logs show: 
![image](https://user-images.githubusercontent.com/66266496/111254841-2036fb80-85d3-11eb-984b-529ab1aa6848.png)

The line in the logs stands out: `Skipping ip-192-168-91-233.us-west-2.compute.internal - no node group config`.
