### ISSUE TITLE
Error : creating an S3 bucket to store pipeline data

### ISSUE THREAD

**Issue by swarnaditya** [aws-samples/eks-workshop#894]
@dalbhanj 

import random, string
HASH = ''.join([random.choice(string.ascii_lowercase) for n in range(3)] + [random.choice(string.digits) for n in range(3)])
AWS_REGION = 'us-west-2'
S3_BUCKET = '{}-kubeflow-pipeline-data'.format(HASH)
!aws s3 mb s3://$S3_BUCKET --region $AWS_REGION

make_bucket failed: s3://qhg411-kubeflow-pipeline-data An error occurred (AccessDenied) when calling the CreateBucket operation: Access Denied

facing this error while creating an S3 bucket to store pipeline data

Checked IAM Roles AmazonEC2ContainerRegistryFullAccess and AmazonS3FullAccess is present.

**Comment by swarnaditya** [comment]
@dalbhanj Pls help

**Comment by dalbhanj** [comment]
So the Jupyter notebook uses Worker node IAM Role and assume permissions to create S3 bucket. Can you check if your worker node IAM role has right permissions?
You can also create S3 bucket outside of notebook and configure S3_BUCKET to use it as well

**Comment by swarnaditya** [comment]
thx @dalbhanj  

i created the bucket manually from portal. while executing the 3rd step  train and test data is getting uploaded 

Training data will be uploaded to: s3://ktq371-kubeflow-pipeline-data/mnist_kmeans_example/train_data
Test data will be uploaded to: s3://ktq371-kubeflow-pipeline-data/mnist_kmeans_example/test_data

After this getting this error 

ClientError                               Traceback (most recent call last)
<ipython-input-46-6a1876726d0c> in <module>
     34 buf.seek(0)
     35 
---> 36 boto3.resource('s3').Bucket(bucket).Object(train_data_key).upload_fileobj(buf)
     37 
     38 # Convert the test data into the format required by the SageMaker KMeans algorithm

/usr/local/lib/python3.6/dist-packages/boto3/s3/inject.py in object_upload_fileobj(self, Fileobj, ExtraArgs, Callback, Config)
    619     return self.meta.client.upload_fileobj(
    620         Fileobj=Fileobj, Bucket=self.bucket_name, Key=self.key,
--> 621         ExtraArgs=ExtraArgs, Callback=Callback, Config=Config)
    622 
    623 

/usr/local/lib/python3.6/dist-packages/boto3/s3/inject.py in upload_fileobj(self, Fileobj, Bucket, Key, ExtraArgs, Callback, Config)
    537             fileobj=Fileobj, bucket=Bucket, key=Key,
    538             extra_args=ExtraArgs, subscribers=subscribers)
--> 539         return future.result()
    540 
    541 

/usr/local/lib/python3.6/dist-packages/s3transfer/futures.py in result(self)
    104             # however if a KeyboardInterrupt is raised we want want to exit
    105             # out of this and propogate the exception.
--> 106             return self._coordinator.result()
    107         except KeyboardInterrupt as e:
    108             self.cancel()

/usr/local/lib/python3.6/dist-packages/s3transfer/futures.py in result(self)
    263         # final result.
    264         if self._exception:
--> 265             raise self._exception
    266         return self._result
    267 

/usr/local/lib/python3.6/dist-packages/s3transfer/tasks.py in __call__(self)
    124             # main() method.
    125             if not self._transfer_coordinator.done():
--> 126                 return self._execute_main(kwargs)
    127         except Exception as e:
    128             self._log_and_set_exception(e)

/usr/local/lib/python3.6/dist-packages/s3transfer/tasks.py in _execute_main(self, kwargs)
    148         )
    149 
--> 150         return_value = self._main(**kwargs)
    151         # If the task is the final task, then set the TransferFuture's
    152         # value to the return value from main().

/usr/local/lib/python3.6/dist-packages/s3transfer/tasks.py in _main(self, client, bucket, key, extra_args)
    331         # Create the multipart upload.
    332         response = client.create_multipart_upload(
--> 333             Bucket=bucket, Key=key, **extra_args)
    334         upload_id = response['UploadId']
    335 

/usr/local/lib/python3.6/dist-packages/botocore/client.py in _api_call(self, *args, **kwargs)
    314                     "%s() only accepts keyword arguments." % py_operation_name)
    315             # The "self" in this scope is referring to the BaseClient.
--> 316             return self._make_api_call(operation_name, kwargs)
    317 
    318         _api_call.__name__ = str(py_operation_name)

/usr/local/lib/python3.6/dist-packages/botocore/client.py in _make_api_call(self, operation_name, api_params)
    633             error_code = parsed_response.get("Error", {}).get("Code")
    634             error_class = self.exceptions.from_code(error_code)
--> 635             raise error_class(parsed_response, operation_name)
    636         else:
    637             return parsed_response

ClientError: An error occurred (AccessDenied) when calling the CreateMultipartUpload operation: Access Denied

**Comment by swarnaditya** [comment]
however i checked the KF fairing S3 and ECR Permission. when i checked echo $ROLE_NAME it was blank 

i tried to execute the below command but no luck 

aws iam attach-role-policy --role-name $ROLE_NAME --policy-arn arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryFullAccess

aws iam attach-role-policy --role-name $ROLE_NAME --policy-arn arn:aws:iam::aws:policy/AmazonS3FullAccess

policy-arn arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryFullAccess
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help
aws: error: argument --role-name: expected one argument

my aws cli is 2.0.38 and i m using linux box

**Comment by brentley** [comment]
we set the ROLE_NAME here:
https://www.eksworkshop.com/030_eksctl/test/#export-the-worker-role-name-for-use-throughout-the-workshop

Can you check to see that you ran that command, had the correct cluster name, and that the command set the variable correctly?

**Comment by swarnaditya** [comment]
Billion Thanks @brentley & @dalbhanj  . Issue got resolved after stetting the variable correctly.  

Thanks Again :) Happy Weekend now :)
