### ISSUE TITLE
Trying to build MNIST model and batch jobs without train job in SageMaker via Kubeflow Pipeline

### ISSUE THREAD

**Issue by swarnaditya** [aws-samples/eks-workshop#896]
@dalbhanj @brentley 

I am trying to create MNIST model , Prediction and Batch Transform in SageMaker without training jobs in SageMaker.

I have removed the HPO and training part from the script and run only the MNIST model , Prediction and Batch Transform part but Code automatically re redeploying HPO and training part also which I dont want in SageMaker.

Thanks in advance 👍

**Comment by dalbhanj** [comment]
Hi @swarnaditya, let me see if I understand your use case. Are you trying to run all steps of Mnist pipeline in Kubernetes? Can you review the sample provided here: https://github.com/aws-samples/eks-kubeflow-workshop/blob/master/notebooks/05_Kubeflow_Pipeline/05_03_Pipeline_mnist.ipynb

This notebook will run all the steps of pipeline on EKS and Not on Sagemaker. If you need to offload some of the steps to Sagemaker, you can review 05_04_Pipeline_SageMaker.ipynb example and replicate that in your use case. For ex, run training and model creation job on EKS and expose inference endpoint on Sagemaker

**Comment by swarnaditya** [comment]
@dalbhanj


We are trying to create a MNIST model on AWS Sagemaker (SM) using kubeflow component

The main goal is like building a hybrid pipeline kind of workflow (some part like inference on Kubeflow and creation of the model and do the batch Transfromation jobs on AWS Sagemaker.

Anyway I will try your steps as you mentioned.
