### ISSUE TITLE
kubeflow deploy fail error gzip: invalid header filename="kfconfig/types.go:524"

### ISSUE THREAD

**Issue by danasaur** [aws-samples/eks-workshop#917]
I went step by step exactly through the following three tutorials:

https://www.eksworkshop.com/020_prerequisites/
https://www.eksworkshop.com/030_eksctl/
https://www.eksworkshop.com/advanced/420_kubeflow/

got to https://www.eksworkshop.com/advanced/420_kubeflow/install/

$ kfctl apply -V -f ${CONFIG_FILE}

<img width="1196" alt="Screen Shot 2020-09-05 at 5 22 08 PM" src="https://user-images.githubusercontent.com/320703/92349054-cdabde00-f089-11ea-9d7c-cd2d2f8c044d.png">

I tested that I am able to manually extract the folder contents with:

$ curl -L https://github.com/kubeflow/manifests/archive/v1.0.1.tar.gz > test.tgz

$ tar zxvf test.tgz

**Comment by henrybravo** [comment]
> I went step by step exactly through the following three tutorials:
> 
> https://www.eksworkshop.com/020_prerequisites/
> https://www.eksworkshop.com/030_eksctl/
> https://www.eksworkshop.com/advanced/420_kubeflow/
> 
> got to https://www.eksworkshop.com/advanced/420_kubeflow/install/
> 
> $ kfctl apply -V -f ${CONFIG_FILE}
> 
> <img alt="Screen Shot 2020-09-05 at 5 22 08 PM" width="1196" src="https://user-images.githubusercontent.com/320703/92349054-cdabde00-f089-11ea-9d7c-cd2d2f8c044d.png">
> 
> I tested that I am able to manually extract the folder contents with:
> 
> $ curl -L https://github.com/kubeflow/manifests/archive/v1.0.1.tar.gz > test.tgz
> 
> $ tar zxvf test.tgz

Hello Dana,

use this newer 1.1.0 version: https://raw.githubusercontent.com/kubeflow/manifests/v1.1-branch/kfdef/kfctl_aws.v1.1.0.yaml and just change the region in line 116 if necessary. For more details see: https://www.kubeflow.org/docs/aws/deploy/install-kubeflow/
