### ISSUE TITLE
Outdated information in Assigning Pods to Nodes section

### ISSUE THREAD

**Issue by petrokashlikov** [aws-samples/eks-workshop#933]
Hi, I would like to report that there is outdated information in this section https://www.eksworkshop.com/beginner/140_assigning_pods/affinity/ 

Node affinity (beta feature). - Node affinity is not a beta feature anymore for quite some time. Can we please remove beta reference?

**Comment by fmedery** [comment]
Thank you for the report, PR has been submitted.
