### ISSUE TITLE
EFS chapter - Reference to non-existing file efs-pv.yaml

### ISSUE THREAD

**Issue by avshabavsha** [aws-samples/eks-workshop#938]
Hello,

under the page: https://www.eksworkshop.com/beginner/190_efs/efs-csi-driver/

There's a reference to the following file, however it doesn't exist :
https://eksworkshop.com/beginner/190_efs/efs.files/efs-pv.yaml
(closest is efs-pvc.yaml)

Could you please check?

The video does not include explanation for the CSI DRIVER, so there might be additional mismatch or .
For example in current explanations there's no reference to 'efs-provisioner-deployment.yaml' which I see still exist in git, so not clear if required or there is missing information in the walkthrough.

Thanks!

**Comment by jihed** [comment]
We referenced [efs-pvc.yaml](https://eksworkshop.com/beginner/190_efs/efs.files/efs-pvc.yaml) to create: `pv`, `pvc`, `storageclass` and `namespace`.

```
kubectl create -f efs-pvc.yaml
namespace/storage created
storageclass.storage.k8s.io/efs-sc created
persistentvolume/efs-pvc created
persistentvolumeclaim/efs-storage-claim created
```

**Comment by fmedery** [comment]
Thank you for the issue.

Hello we updated the lab and since then I am unable to reproduce the bug you mentioned.

Can you try again ?

Tx
