### ISSUE TITLE
Helm install for EFS CSI driver is broken

### ISSUE THREAD

**Issue by rizblie** [aws-samples/eks-workshop#971]
Content page: https://github.com/aws-samples/eks-workshop/blob/main/content/beginner/190_efs/efs-csi-driver.md

On latest EKS K8S version 1.17, the recommended helm install procedure for EFS CSI driver fails:
```
helm repo add aws-efs-csi-driver https://kubernetes-sigs.github.io/aws-efs-csi-driver/
helm install aws-efs-csi-driver aws-efs-csi-driver/aws-efs-csi-driver
```
Ouptut:
```
Error: rendered manifests contain a resource that already exists. Unable to continue with install: CSIDriver "efs.csi.aws.com" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "aws-efs-csi-driver"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "default"
```

**Comment by jihed** [comment]
Hello,

It seems to me some resources were created outside helm (or an old version of hlem) and when you tried to install this release: Helm was not able to manage it.  I suggest to try to import the resource to de be managed by Helm (3.2 or later) or just do a clean up and try again.

I tried to the procedure on EKS (k8s 1.17) using helm 3.3.4 and it works fine.

HTH,

**Comment by fmedery** [comment]
Hello thank yoy for the feedback,
we switch to `kubectl -k` to handle the installation. 
PR: #967 

Also you can follow this issue for the helm installation:
https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/270/files
