### ISSUE TITLE
Documentation Enhancement: Deploying Jenkins > Set up Multibranch Projects 

### ISSUE THREAD

**Issue by Sebbenbear** [aws-samples/eks-workshop#974]
When creating an item in the Jenkins UI, some customers don't select the CodeCommit credentials set from the dropdown, after entering them. The job cannot run unless these are actually set, and this step is easy to miss.

This can be resolved by noting this in the documentation.

**Comment by fmedery** [comment]
thank you for creation this issue, a PR is in the approved queue to fix it
