### ISSUE TITLE
Hard coded AWS Regions

### ISSUE THREAD

**Issue by cloudlessk** [aws-samples/eks-workshop#977]
Within the Jenkins lab (https://www.eksworkshop.com/intermediate/210_jenkins/codecommit/) , there is a hardcode of US-WEST-2. 

`git clone codecommit::us-west-2://eksworkshop-app`

This errors out when using US-EAST-2 but is fixed when the command is changed to the below. 
 
`git clone://eksworkshop-app`

Additionally, within the Pod Affinity section (https://www.eksworkshop.com/beginner/140_assigning_pods/affinity/), 

The first command of us-west-2 causes confusion if just immediately copied:

`kubectl label nodes ip-192-168-15-64.us-west-2.compute.internal azname=az1`

Use of the below can be clearer for users:

`kubectl label nodes <node-name> azname=az1`

**Comment by fmedery** [comment]
That you for reporting the issue, a PR will be ready later this week
