### ISSUE TITLE
Create Elasticsearch Domain Command Fails

### ISSUE THREAD

**Issue by ScottyVG** [aws-samples/eks-workshop#988]
When trying to set up an elasticsearch domain following the eks-workshop guide, I get the following `Parameter Validation Failed` errors when running the following command:
```
$ aws es create-elasticsearch-domain \
  --cli-input-json  file://~/environment/logging/es_domain.json
``` 
I've double-checked all of my environment variables that I've set and check the es_domain.json file for any errors, but I still get the following error message when I run that command:
```
Parameter validation failed:
Unknown parameter in input: "DomainEndpointOptions", must be one of: DomainName, ElasticsearchVersion, ElasticsearchClusterConfig, EBSOptions, AccessPolicies, SnapshotOptions, VPCOptions, CognitoOptions, EncryptionAtRestOptions, NodeToNodeEncryptionOptions, AdvancedOptions, LogPublishingOptions
Unknown parameter in input: "AdvancedSecurityOptions", must be one of: DomainName, ElasticsearchVersion, ElasticsearchClusterConfig, EBSOptions, AccessPolicies, SnapshotOptions, VPCOptions, CognitoOptions, EncryptionAtRestOptions, NodeToNodeEncryptionOptions, AdvancedOptions, LogPublishingOptions
Unknown parameter in ElasticsearchClusterConfig: "WarmEnabled", must be one of: InstanceType, InstanceCount, DedicatedMasterEnabled, ZoneAwarenessEnabled, ZoneAwarenessConfig, DedicatedMasterType, DedicatedMasterCount
```

I checked the [es cli reference](https://docs.aws.amazon.com/cli/latest/reference/es/create-elasticsearch-domain.html), and I don't see any changes to the `DomainEndpointOptions`, `AdvancedSecurityOptions`, or the ` WarmEnabled` Parameters. When I remove these parameters from the es_domain.json file, I get the error:

```
An error occurred (ValidationException) when calling the CreateElasticsearchDomain operation: Enable fine-grained access control or apply a restrictive access policy to your domain
```

So I'm not sure what to do to enable fine-grained access control on the es cluster to move on to the next step.

**Comment by fmedery** [comment]
Hello, thank you for the report.
I just did the lab without any error. Can you post your the `es_domain.json` file generated by the command in this page: http://localhost:8080/intermediate/230_logging/setup_es/

**Comment by fmedery** [comment]
Do not hesitate to re open this issue if you still have the problem.
Kind Regards,
